-- Batch 10: Companies 91 to 100

-- BANDERA LUIGI COSTRUZIONI MECCANICHE SPA (ID: 1119)
UPDATE companies SET email = 'lbandera@lbandera.com', phone = '+39 0331 398-111', website = 'https://luigibandera.com', products_services = 'Extruders, All product categories', sales_volume = '20 - 100 Mill. US $', export_content = '> 75%', employees_count = '101 - 500', foundation_year = '1947', target_groups = 'Machinery construction, Social networks, Visit the exhibitor on the following social networks, Visit us on Instagram, Visit us on LinkedIn, Visit us on TikTok, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1119;

-- Beologic NV (ID: 1055)
UPDATE companies SET email = 'info@beologic.com', phone = '+32 56 735325', website = 'https://www.beologic.com', company_description = 'Sustainability can be challenging – we help you make it work

At Beologic, we create thermoplastic pellets and powders for injection molding, rotational molding, and extrusion. With over 20 years of expertise, we combine innovation and sustainability to deliver ...', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, PLA (polylactic acid, Polymilchsäure), Compounds/Blends, Compounds, natural fiber reinforced, Wood Plastic Composites (WPC), Dry blend, Granulates, Wood-flour-filled polypropylene (WD-PP), Record compounds, Polyethylene, low density, Polyethylene, high density, Polypropylene, Compounds/Recyclates, Rotational moulding machines, Extrusion dies, Science and consulting, All product categories', detailed_address = 'As a trusted partner and leading expert in sustainable thermoplastic compounds, we help you balance materials, processes and production for a greener future. Together, we’re shaping a plastics industry that works for your products and the planet.', employees_count = '11 - 30', foundation_year = '2002', target_groups = 'Plastic product manufacturing,, Machinery construction,, Construction / building and living,, Agriculture,, Sports / leisure,, Other industries, Downloads, Beograde, Extrusion, Injection moulding, Rebound - vinyl pressing, Rotomoulding, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1055;

-- Addiplast Group S.A.S. (ID: 1088)
UPDATE companies SET email = 'contact@addiplast-group.com', phone = '+33 4 71751090', website = 'https://www.addiplast-group.com', company_description = 'Addiplast Group is a family-owned French company and a European leader in the design and production of high-performance thermoplastic compounds and color & fonctional masterbatches. Since 1986, we have combined cutting-edge R&D capabilities with flexible ...', products_services = 'Bioplastics, biobased, Bio-Polyamides, Compounds/Blends, Compounds, natural fiber reinforced, Compounds (Polymer blends), Granulates, Masterbatches, Polyamides blends, Polyamide PA 11, Polyamide PA 12, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polyketone, Polyphenylene ether (PPE) modified, Polypropylene, Polyvinylidene fluoride (PVDF), Thermoplastic elastomers, biobased, Polypropylene, Polyamide, Hot melt adhesives, Color Masterbatches, Raw materials, Cable compounds, Compounds/Recyclates, Subcontracting, All product categories', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 75%', employees_count = '101 - 500', foundation_year = '1986', target_groups = 'Plastic product manufacturing, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1088;

-- FKuR Kunststoff GmbH (ID: 1046)
UPDATE companies SET email = 'sales@fkur.com', phone = '+49 2154 9251-0', website = 'https://www.fkur.com', company_description = 'FKuR is a medium-sized, privately held company focusing on the development, production and marketing of high-quality special compounds and the distribution of plastic specialties and recyclates.

Plastics care for Future – Let`s keep it in the loop.', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Polyethylene terephthalate, biobased (Bio-PET), Polyethylene, biobased (Bio-PE), Bioplastics, cellulose based, Bioplastics, starch based, Compounds/Blends, Compounds, natural fiber reinforced, Ethylene/VAC-copolymers (E/VA), Granulates, Wood-flour-filled polypropylene (WD-PP), Thermoplastic elastomers, biobased, Polyethylene, low density, Polyethylene, high density, Polypropylene, Compounds/Recyclates, All product categories', detailed_address = 'Our customers are our partners, we accompany them throughout the entire project: We recommend the most suitable plastic - be it bio-based, biodegradable or recycled - for the given application or develop an individual compound on request. As we have a broad network of reliable partners at our disposal, we can bring brand owners together with the appropriate processor. During the implementation phase, extensive technical support, including on-site customer support, is a matter of course for us. Finally, we support our customers with marketing-relevant questions within the framework of a successful market launch.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1046;

-- Sukano AG (ID: 1133)
UPDATE companies SET email = 'media@sukano.com', phone = '+41 44 7875777', website = 'https://sukano.com', company_description = 'Sukano is a global specialist in the development and production of additive and color masterbatches and compounds for polyesters, biopolymers, high-temperature polymers, and specialty resins. The company is driven by expertise and devotes its technical knowledge ...', products_services = 'Bioplastics, biobased, Compounds (Polymer blends), Masterbatches, Polyethylene terephthalate (PET), Additives, other, Additives for laser transmission welding, Additive concentrates, Antiblocking agents, Antistatic agents, Biodegradable additives, Fire protection agents, Extender, Color Masterbatches, Nucleating agent (see 1.10.81 Nucleating agents), Light stabilisers (s. UV stabilizers), Additives, Matting agent, Nucleating agents, Optical brighteners, Impact modifiers, UV stabilizer, Mould release agents, Compounds/Recyclates, All product categories', foundation_year = '1988', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Construction / building and living,, Medical technology / precision engineering / optics, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1133;

-- LIFELINE TECHNOLOGIES (ID: 1218)
UPDATE companies SET email = 'jayshree.jadhav@lifelinetechnologies.in', phone = '+91 98218 56789', website = 'https://www.lifelinetechnologies.in', products_services = 'Additive concentrates, Biodegradable additives, Color Masterbatches, Additives, UV stabilizer, All product categories', detailed_address = '400705Navi Mumbai Maharashtra', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1218;

-- TEKU GmbH Fluorkunststoffe (ID: 1024)
UPDATE companies SET email = 'info@teku-gmbh.de', phone = '+49 2051 2803-0', website = 'https://www.teku-gmbh.de', products_services = 'Polyetheretherketone (PEEK), Polytetrafluoroethylene (PTFE), Parts made by mechanical treating, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for electrical engineering, Plastics products and parts for data appliance, Plastics products and parts for aviation, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Semi finished products of polytetrafluorethylene (PTFE), Armatures and parts, Sealings/Sealrings, Bellows, expansible, Parts for pumps, Technical films, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1024;

-- Blend Colours Pvt. Ltd. (ID: 1207)
UPDATE companies SET email = 'shailesh@blendcolours.com', phone = '+91 40 24361499', website = 'https://www.blendcolours.com', company_description = 'Blend Colours is a leading manufacturer of all types of masterbatches, fillers and compounds from India, recognised as ‘two star export house’.

Technology has always been a key differentiator for Blend Colours, which has notably benefited its customers and has ...', products_services = 'Bioplastics, biologically degradable, Masterbatches, Polyester fibres, Polypropylene fibres, Color Masterbatches, Additives, Pigment Black, Pigment Black Preparations, UV stabilizer, All product categories', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1999', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Other industries, Downloads, Blend Colours Brochure - 2024 (3), Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on X, Visit us on WhatsApp, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1207;

-- SIMONA AG (ID: 1028)
UPDATE companies SET email = 'mail@simona-group.com', phone = '+49 6752 14-0', website = 'https://www.simona.de', products_services = 'Products made by extrusion, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for agriculture, Plastics products and parts for aviation, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of polyethylene (PE), Semi finished products of polypropylene (PP), Semi finished products of polyvinylchloride (PVC), other and machined semi finished products / Pre-cut parts, All product categories', employees_count = '> 500', foundation_year = 'technical service centre, the newly created busine', target_groups = 'Plastic product manufacturing,, Trade, services, Downloads, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on Instagram, Visit us on LinkedIn, Visit us on XING, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1028;

-- Mitras Materials GmbH (ID: 1027)
UPDATE companies SET email = 'info@mitras-materials.com', phone = '+49 961 89308', website = 'https://www.mitras-materials.com', products_services = 'Products made by extrusion, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for furniture appliances, Plastics products and parts for transport/packaging, Semi finished products of acryl-nitrile-butadiene (ABS), Semi finished products of polycarbonate (PC), Semi finished products of polymethylmethacrylate (PMMA), Semi finished products of polystyrene (PS), Technical films, Composite boards, All product categories', detailed_address = 'Our brand THERMODET® stands for high-quality thermoplastic sheets for demanding thermoformed parts or elegant plane applications. The wide range of our various composite sheets is suitable for many technical and design-oriented requirements.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1027;

