-- Batch 18: Companies 171 to 180

-- Omya GmbH (ID: 1070)
UPDATE companies SET email = 'info.polymers@omya.com', phone = '+49 221 3775-224', website = 'https://www.omya.com', company_description = 'Omya is a leading global producer of essential minerals and a worldwide distributor of specialty materials. Founded in Switzerland in 1884 and privately owned, we employ 9,000 people across 160 plants in 50 countries. Omya provides added-value products and services from ...', products_services = 'Acrylonitrile/butadiene/styrene polymerblends, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Compounds/Blends, Chlorinated polyethylene (CPE), Self-reinforcing plastics (LCP=liquid crystal polymers), Masterbatches, Polyamides blends, Polybutylene terephthalate (PBT), Polycarbonate (PC), Polycarbonate blends, Polyketone, Polyphenylene sulfide (PPS), Polyurethane thermoplastic (PUR), Polyvinyl chloride expandable, Impact modifier, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Epoxy resins (EP), Ethylene/vinyl acetate foams (EVA), Polyethylene foams (PE), Polyurethane casting resins rigid foams-systems, Polyurethane casting resins semi-rigid foams-systems, Polyurethane casting resins flexible foams-systems, Chloroprene rubber (CR), Ethylene/propylene terpolymers (EPDM), Styrene/butadiene rubber (SBR), Adipates, Ageing stabilizers, Aluminium trihydrate, Antiblocking agents, Antimony trioxide, Antioxidants, Antifoam agents, Antislip agents, Antistatic agents, Accelerators, Biodegradable additives, Agents biozides, Fire protection agents, Colour pigments, Ca/Zn-Stabilisers, Dispersing agents, Effect pigments, Color Masterbatches, Colourants, Lubricants, Hardener (EP resins), Light stabilisers (s. UV stabilizers), Nucleating agents, Impact modifiers, Stabilizers, Stearic acid, Crosslinking agents, Vulcanisation accelerator, Vulcanising agents, Waxes, White pigments, Aluminium hydroxide, Bari', main_email = 'marco.viel@omya.com', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1884', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Agriculture, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1070;

-- L. Brüggemann GmbH & Co. KG (ID: 1151)
UPDATE companies SET email = 'info@brueggemann.com', phone = '+49 7131 1575-0', website = 'https://www.brueggemann.com', products_services = 'Masterbatches, Additives, other, Additive concentrates, Ageing stabilizers, Antioxidants, Extender, Flow auxiliaries, Lubricants, Nucleating agent (see 1.10.81 Nucleating agents), Additives, Nucleating agents, Impact modifiers, Stabilizers, Processing auxiliaries, Waxes, Caprolactam, Polymerization auxiliaries, Polymerization-catalysts, Subcontracting, All product categories', target_groups = 'of the future. We provide the crucial link across many application areas - and have been doing so for 150 years now.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1151;

-- PREMIUM (ID: 1036)
UPDATE companies SET email = 'info@bieglo.com', phone = '+49 40 401130000', website = 'https://www.bieglo.com', company_description = 'The BIEGLO GmbH is a Hamburg-based distribution company specialized in high-performance polymers. Together with our U.S. subsidiary BARplast LLC, which serves the American market, we offer premium thermoplastics such as PEEK, PI (Polyimide), PBI, TPI, and PAI in various ...', products_services = 'Polyamideimide, Polyaryletherketone (PAEK), Polybenzimidazoles, Polyetheretherketone (PEEK), Polyetherimide (PEI), TPV-thermoplastic vulcanised material, Polyimide foams, Plastics products and parts for aviation, Semi finished parts/products made from Polyimide, Parts from high performance thermoplastics, Sealings/Sealrings, Technical films, All product categories', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Machinery construction,, Vehicle construction / aerospace,, Electronics / electro technology,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Other industries, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1036;

-- SANGIR PLASTICS PVT LTD (ID: 1020)
UPDATE companies SET email = 'k2025@sangir.com', website = 'https://www.sangir.com', company_description = 'We are Sangir, a major producer of specialty thermoplastic solutions and a major supplier to diverse industries and projects.

Sangir  is certified for  ISO 9001-2015 and also accredited with  ISO 14001:2015  &  ISO 45001-2018  Certifications...', products_services = 'Products made by extrusion, Parts made by mechanical treating, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of polyethylene (PE), Semi finished products of polypropylene (PP), Semi finished products of polyvinylchloride (PVC), Parts from engineering plastics, Fibreglass-reinforced plastic parts, All product categories', detailed_address = 'Sangir  is certified for  ISO 9001-2015 and also accredited with  ISO 14001:2015  &  ISO 45001-2018  Certifications. Our Dunn & Bradstreet No. is D&B D-U-N-S® NUMBER:  91-613-2368 .', foundation_year = 'a state-of-the-art thermoplastic machining and fab', target_groups = 'Plastic product manufacturing, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on X, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1020;

-- AF-COLOR Zweigniederlassung der AKRO-PLASTIC GmbH (ID: 1213)
UPDATE companies SET email = 'info@af-color.com', phone = '+49 2636 80920', website = 'https://www.af-color.com', company_description = 'Customized masterbatch formulations for your application

In every industry, color and function shape the properties and brand image of plastic products. AF-COLOR is your specialist for both commercially available and high-quality technical ...', products_services = 'Masterbatches, Additives, Purging compound, All product categories', employees_count = '31 - 100', foundation_year = '2003', target_groups = 'Plastic product manufacturing, Downloads, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1213;

-- Miracll Chemicals Co., Ltd. (ID: 1102)
UPDATE companies SET email = 'miracll@miracll.com', phone = '+86 535 39798988065', website = 'https://www.miracll.com', company_description = 'Miracll Chemicals Co., Ltd. was established in 2009, listed company (Code: 300848.SZ), the core products are Thermoplastic Polyurethane Elastomer(TPU), Reactive Polyurethane Hot Melt Adhesive(PUR), Water-Borne Polyurethane(PUD), Biodegradable material (PBS), Isocyanates ...', products_services = 'Polyurethane, biobased, All product categories', detailed_address = 'No. 35 Changsha Road Development District', foundation_year = '2009', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing, Downloads, 美瑞新材-产品手册（英文版）_2025V1-0328, Miracll Isocyanates&Amines Product Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1102;

-- BERKIM KAUCUK PLASTIK KIMYA SAN. VE TIC. A.S. (ID: 1103)
UPDATE companies SET email = 'info@berkimkimya.com.tr', phone = '+90 264 3535327', website = 'https://www.berkimkimya.com.tr', products_services = 'Additives, other, All product categories', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing, Downloads, BERKIM CATALOG 2024, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1103;

-- Dow (ID: 1056)
UPDATE companies SET email = 'info@dow.com', phone = '+41 44 7282111', website = 'https://www.dow.com', company_description = 'Dow (NYSE: DOW) Packaging & Specialty Plastics (P&SP), a business unit of Dow, combines core strengths of R&D, worldwide reach, broad product lines and industry expertise to deliver high performing technologies for end use markets in food packaging, personal ...', products_services = 'Polyethylene, biobased (Bio-PE), Wood Plastic Composites (WPC), Ethylene/VAC-copolymers (E/VA), Ionomers, Polyethylene blends, Polyethylene PE-HD, Polyethylene PE-LD, Polyethylene PE-LLD, Polyethylene PE-MD, Olefin copolymers (EP(D)M), Olefin based thermoplastic elastomer, TPO, Polyethylene, low density, Polyethylene, high density, Hot melt adhesives, All product categories', main_email = 'jfelber@dow.com', detailed_address = 'Dow (NYSE: DOW) Packaging & Specialty Plastics (P&SP), a business unit of Dow, combines core strengths of R&D, worldwide reach, broad product lines and industry expertise to deliver high performing technologies for end use markets in food packaging, personal hygiene, infrastructure, consumer goods and mobility. Dow P&SP is one of the world''s largest producers of polyethylene resins, functional polymers, and adhesives, and enabled by Pack Studios, is a leading innovator and collaborator across the value chain on sustainable application development and circular economy life-cycle design for plastics. www.dowpackaging.com.', target_groups = 'Plastic product manufacturing,, Chemical industry, Downloads, The materials ecosystem- Unlocking the value of waste, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1056;

-- BEN Kunststoffe Vertriebs- GmbH (ID: 1012)
UPDATE companies SET email = 'info@ben-plastic.com', phone = '+49 7072 9187-87', website = 'https://www.ben-plastic.com', products_services = 'Products made by extrusion, Parts made by mechanical treating, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for electrical engineering, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for furniture appliances, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of polyethylene (PE), Semi finished products of polypropylene (PP), Semi finished products of polyvinylchloride (PVC), other and machined semi finished products / Pre-cut parts, Parts from standard plastics, Parts from engineering plastics, All product categories', detailed_address = 'High product quality and reliable service are the strengths with which we convince versatile customers from trade, industry, chemistry, advertising, construction and electrical engineering at home and abroad.', employees_count = '101 - 500', foundation_year = '1989', target_groups = 'Plastic product manufacturing,, Chemical industry,, Machinery construction,, Vehicle construction / aerospace,, Electronics / electro technology,, Medical technology / precision engineering / optics,, Agriculture,, Sports / leisure,, Other industries,, Trade, services,, Universities, technical colleges,, Craft, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1012;

-- Mitsubishi Chemical Europe GmbH (ID: 1013)
UPDATE companies SET email = 'info-mce@m-chem.com', phone = '+49 211 52054-0', website = 'https://eu.mitsubishi-chemical.com/about-us/', products_services = 'Acetal homo and copolymers (POM), Barrier plastics, Bioplastics, biobased, Bioplastics, biologically degradable, Bio-Polyamides, Polybutylene succinate (PBS), Polybutylene succinate-co-adipate (PBSA), Polyesters, Polyurethane, bio-based, Compounds/Blends, Copolyamide TPE-E, TPE-A/PEBA, Cycloolefine Polymers, Electrically conductive plastics, Ethylene/vinyl alcohol copolymers (E/VAL), Polyarylamide (PA MXD6), Polybutylene terephthalate (PBT), Polycarbonate (PC), Polycarbonate blends, Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene ether (PPE) modified, Polypropylene, Polyvinyl alcohol (PVAL), Polyvinyl chloride plasticised (PVC-P), Polyvinyl chloride rigid (PVC-U), Polyvinyl chloride expandable, Polyvinyl chloride blends, Polyvinyl chloride copolymers, Prepregs, thermoplastic, Reclaimed material, Polyurethane, biobased, Thermoplastic elastomers, biobased, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Thermoplastic elastomers based on PVC, TPE/PVC, Olefin based thermoplastic elastomer, TPO, TPV-thermoplastic vulcanised material, SMC (sheet moulding compounds), Polyethylene, high density, Other thermoplastics, e.g. POM, PC, PBT, Polyester, Linings and coatings, Cable compounds, Products made by extrusion, Parts made by compression moulding, Parts made by injection moulding, Parts made by thermoforming, Plastics products and parts for automotive, Plastics products and parts for electrical ', sales_volume = 'of 3,976.9 billion yen ($30 billion USD) in the fiscal year ended March 31, 2022.', employees_count = 'around the world support people''s daily lives and global businesses by providing advanced chemistry-', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1013;

