-- Batch 6: Companies 51 to 60

-- BDL S.R.L. (ID: 1123)
UPDATE companies SET email = 'info@bidielle.com', phone = '+39 0522 922521', website = 'https://www.bidielle.com', company_description = 'For over 40 years, BDL has been dedicated to the manufacturing of plastic injection molds. A constant commitment to quality has led to the creation of a flexible and dynamic structure, capable of offering each client tailored solutions to their specific needs.', products_services = 'Injection and compression moulds, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '31 - 100', foundation_year = '1977', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Medical technology / precision engineering / optics, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1123;

-- Axia Plastics LLC (ID: 1089)
UPDATE companies SET email = 'poliveira@vinmar.com', phone = '+31 61 5689952', website = 'https://axiaplastics.com', products_services = 'Polypropylene, Olefin based thermoplastic elastomer, TPO, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1089;

-- Dynasol Group (ID: 1073)
UPDATE companies SET email = 'daniela.quintero@dynasol.com', phone = '+1 281 8851700', website = 'https://dynasolgroup.com', products_services = 'Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1073;

-- Us Masterbatch Joint Stock Company (ID: 1196)
UPDATE companies SET email = 'info@usmasterbatch.com', phone = '+84 24 6682771', website = 'https://usmasterbatch.com', products_services = 'Masterbatches, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1196;

-- Polymer-Service PSG GmbH (ID: 1084)
UPDATE companies SET email = 'info@polymer-service.de', phone = '+49 40 30902-400', website = 'https://www.polymer-service.de', products_services = 'Acrylonitrile/butadiene/styrene polymerblends, Copolyester TPE-O, COPE, Ethylene/tetrafluoroethylene copolymers (E/TFE), Masterbatches, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polycarbonate (PC), Polycarbonate blends, Polyetheretherketone (PEEK), Polyethersulfone (PES, PESU), Polyketone, Polyphenylene sulfide (PPS), Polypropylene, Polysulfone (PSU), Polytetrafluoroethylene (PTFE), Polyvinylidene fluoride (PVDF), Reclaimed material, Tetrafluoroethylene/perfluoroalkylvinylether copolymers (PFA), Tetrafluoroethylene/perfluoropropylene copolymers (FEP), Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Olefin based thermoplastic elastomer, TPO, Polyamide, Foaming agents, Subcontracting, All product categories', foundation_year = 'itself as a medium-sized, competent partner of the', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1084;

-- AISA Automation Industrielle S.A. (ID: 1112)
UPDATE companies SET email = 'info@aisa.com', phone = '+41 24 4820110', website = 'https://www.aisa.com', company_description = 'High-tech machines to produce plastic and laminated tube packaging—primarily used in the cosmetics, pharmaceutical, food, and personal care sectors—are our area of expertise. With over 60 years, AISA Automation Industrielle SA stands out for its know-how in development and ...', products_services = 'Parts made by injection moulding, Welding, Recycling plants for mixed waste, Injection moulding machines, multi-station, Compression and transfer moulding presses for plastics, Equipment for In-Mould-Labeling (IML), High-frequency welding machines, Science and consulting, All product categories', employees_count = '101 - 500', foundation_year = '1962', target_groups = 'Packaging / distribution, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1112;

-- Soltex Petroproducts Ltd. (ID: 1202)
UPDATE companies SET email = 'ed@soltexpetro.com', phone = '+91 22 4063151502', website = 'https://www.soltexpetro.com', company_description = 'Soltex Petroproducts Ltd. is a leading producer of master batches from India with over 30 years of manufacturing expertise.

We offer master batches like White, Black, Sodium & Color master batches as well as Additives like Anti block, ...', products_services = 'Color Masterbatches, All product categories', detailed_address = '5 ( Mumbai, Daman, Silvassa, Kolkata & Uttarakhand)', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 25%', employees_count = '> 500', foundation_year = '1992', target_groups = 'Plastic product manufacturing,, Packaging / distribution, Downloads, Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on WhatsApp, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1202;

-- M.J. Additive GmbH (ID: 1157)
UPDATE companies SET email = 'service@mj-additive.com', phone = '+49 2924 9706-0', website = 'https://www.mj-additive.com', products_services = 'Additives, other, Additive concentrates, Antiblocking agents, Antioxidants, Antislip agents, Antistatic agents, Dispersing agents, Flow auxiliaries, Lubricants, Light stabilisers (s. UV stabilizers), Additives, Nucleating agents, Stabilizers, UV stabilizer, Mould release agents, Raw materials, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1157;

-- CGC TECHNOLOGY INTERNATIONAL LIMITED (ID: 1099)
UPDATE companies SET email = 'isabella.yang@chinapelletizer.com', phone = '+852 852 66627518', company_description = 'CGC Technology International Ltd, was established in 2010, is specialized in the development and manufacturing of Underwater Pelletizers and Spare Parts for machinery used in the plastics industry, offering customized and innovative solutions to meet any need in underwater ...', products_services = 'Pelletizers, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 25%', employees_count = '101 - 500', foundation_year = '2010', target_groups = 'Machinery construction, Downloads, UWP® Underwater Pelletizing System, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1099;

-- ROWA Lack GmbH (ID: 1172)
UPDATE companies SET email = 'info@rowa-lack.de', phone = '+49 4101 706-01', website = 'https://www.rowa-lack.de', company_description = 'ROWA GmbH was founded in 1958 in Seevetal near Hamburg as a rubber processing company. From 1969, the company also produced high-quality coating systems, matting agent concentrates and ...

Proven brand products and individual brands: basic components for a successful result.', products_services = 'Paint auxiliairies, Color Masterbatches, Matting agent, Crosslinking agents, Paints, coatings, Coatings, All product categories', employees_count = '31 - 100', foundation_year = '1958', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Other industries, Downloads, ROWA LACK Company Profile, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1172;

