-- Batch 14: Companies 131 to 140

-- Fraunhofer-Institut für Umwelt-, Sicherheits- und Energietechnik UMSICHT (ID: 1057)
UPDATE companies SET email = 'info@umsicht.fraunhofer.de', phone = '+49 208 8598-0', website = 'https://www.umsicht.fraunhofer.de', company_description = 'Fraunhofer UMSICHT supports industries and society in the transfer to a climate-neutral and circular economic system. Our research focuses on Circular Economy, Green Hydrogen, Carbon Management and Local Energy Systems.', products_services = 'Bioplastics, biobased, Compounds (Polymer blends), Electrically conductive plastics, Ionomers, Biodegradable additives, Science and consulting, All product categories', target_groups = 'and society in the transfer to a climate-neutral and circular economic system. Our research focuses on Circular Economy, Green Hydrogen, Carbon Management and Local Energy Systems.,  We develop materials and processes for the circular use of resources and for the electrochemical production, use and storage of green hydrogen. We also offer solutions for the sustainable use of carbon and develop energy concepts for climate-neutral residential, commercial and industrial sites.,  We combine expertise in process engineering, energy technology and materials development with a comprehensive view of the challenges facing large-scale industry, SMEs and society. We provide holistic utilization advice, point out options for action, weigh them up and develop the best solution in each case., Bookmark, ', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1057;

-- DK Kunststoff-Service GmbH (ID: 1045)
UPDATE companies SET email = 'dk@dk-kunststoffe.de', phone = '+49 521 52044-0', website = 'https://www.dk-kunststoffe.de', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Polyurethane, bio-based, Compounds (Polymer blends), Copolyamide TPE-E, TPE-A/PEBA, Electrically conductive plastics, Polyamides blends, Polyamide PA 12, Polyamide PA 46, Polyamide PA 612, Polyamids PA 06-06-T, Polybutylene terephthalate (PBT), Polyetheretherketone (PEEK), Reclaimed material, Thermoplastic urethane TPE-U/TPU, SEBS-Blockcopolymer, TPV-thermoplastic vulcanised material, Polystyrene, Polyamide, Additives, Purging compound, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1045;

-- K.D. Feddersen GmbH & Co. KG (ID: 1047)
UPDATE companies SET email = 'info@kdfeddersen.com', phone = '+49 40 2350701', website = 'https://www.kdfeddersen.com', company_description = 'Wir sind Ihr Partner, wenn es um die Distribution von hochwertigen technischen Kunststoffen geht.', products_services = 'Acetal homo and copolymers (POM), Acrylic glass (s. PMMA), Acrylonitrile/butadiene/styrene polymerblends, Bioplastics, biobased, Bioplastics, biologically degradable, Bio-Polyamides, Polyesters, Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Granulates, Polyamide PA 06, Polyamide PA 610, Polyamide PA 612, Polyamide PA 66, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polycarbonate (PC), Polycarbonate blends, Polyethylene terephthalate (PET), Polyketone, Polymethylmethacrylate (PMMA) and copolymers (s. acrylic glass), Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene ether blends, Polyphenylene sulfide (PPS), Polypropylene, Polystyrene (PS), Thermoplastic elastomers, biobased, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Olefin based thermoplastic elastomer, TPO, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1047;

-- Polyram – MCT Germany GmbH (ID: 1072)
UPDATE companies SET email = 'yifat@polyram-group.com', phone = '+972 4 6599-968', website = 'https://www.polyram-group.com', products_services = 'Acetal polymerblends, Acrylonitrile/butadiene/styrene polymerblends, Barrier plastics, Compounds/Blends, Compounds (Polymer blends), Polyamides blends, Polybutylene terephthalate blends, Polycarbonate blends, Polyethylene blends, Impact modifier, Styrene polymerblends, Thermoplastic urethane blends TPE-U/TPU, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Maleic resins, Adhesives, Coupling agents, Cable compounds, Purging compound, Compounds/Recyclates, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1072;

-- Biesterfeld Plastic GmbH (ID: 1042)
UPDATE companies SET email = 'contact@biesterfeld.com', phone = '+49 40 32008-0', website = 'https://www.biesterfeld.com', products_services = 'Acetal homo and copolymers (POM), Acetal polymerblends, Acrylic glass (s. PMMA), Acrylonitrile/butadiene/styrene polymerblends, Acrylonitrile/butadiene/styrene copolymers, Acrylonitrile/styrene/acrylic ester copolymerblends, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Barrier plastics, Bioplastics, biobased, Bioplastics, biologically degradable, Bio-Polyamides, Polyethylene, biobased (Bio-PE), PLA (polylactic acid, Polymilchsäure), Polyesters, Compounds/Blends, Bioplastics, Certifications/Standards, Chlorinated polyethylene (CPE), Compounds (Polymer blends), Copolyester TPE-O, COPE, Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Ethylene/chlorotrifluoroethylene copolymers (E/CTFE), Ethylene/methylene acrylate copolymers (E/MA), Ethylene/VAC-copolymers (E/VA), Granulates, Ionomers, Masterbatches, Polyamides blends, Polyamid-Copolymer PA 06-66, Polyamid-Copolymer PA 66-06, Polyamide PA 12, Polyamide PA 06, Polyamide PA 610, Polyamide PA 612, Polyamide PA 06-03-T, Polyamide PA 66, Polyamids PA 06-06-T, Polyaryletherketone (PAEK), Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polycarbonate (PC), Polycarbonate blends, Polyetheretherketone (PEEK), Polyetherimide (PEI), Polyethersulfone (PES, PESU), Polyethylene expandable, Polyethylene crosslinkable, Polyethylene blends, Polyethylene PE-HD, Polyethylene PE-LD, Polyethylene PE-LLD, Polyethylene PE-MD, Polyethylene PE-UHMW, Polyethylene PE-ULD, Polyethylene ', detailed_address = 'Biesterfeld Plastic GmbH is a leading international distributor for the plastics industry. Global polymer producers such as DuPont, ExxonMobil, Celanese, INEOS, BASF, Solvay, CHIMEI and LG Chem rely on the long-standing partnership with Biesterfeld Plastic and have been growing side by side with the company for many decades. With its locally based sales teams and technical engineers, the distributor advises its customers from a wide range of segments. The company makes independent material recommendations, advises on product development, process optimisation and offers customised commercial and logistical solutions.', sales_volume = 'of 1.4 billion EUR. The fully family-owned company operates in the business divisions Biesterfeld Pl', employees_count = 'across 50 locations in Europe, North and South America, Asia and Africa and generates an annual reve', foundation_year = 'in 1906 in Hamburg, Germany, today the group has m', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1042;

-- Amandus Kahl GmbH & Co. KG (ID: 1114)
UPDATE companies SET email = 'info@akahl.de', phone = '+49 40 72771-0', website = 'https://www.akahl.com', products_services = 'Two roll mills, Size reduction equipment (crushers, shredders, grinders), Screening machines, classifiers, dedusting systems for plastic pellets, Extruders, Compression and transfer moulding presses for plastics, Compression and transfer moulding presses for rubber, Compression and transfer moulding presses for composites, All product categories', employees_count = 'ensure smooth operations within the group.', target_groups = ', such as food, pet food, chemical-pharmaceutical, and the waste disposal and recycling industries.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1114;

-- Axens SA (ID: 1167)
UPDATE companies SET products_services = 'Recycling plants for mixed waste, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1167;

-- BioCote Ltd (ID: 1221)
UPDATE companies SET email = 'Biocote@biocote.com', phone = '+44 24 2477712489', website = 'https://www.biocote.com', company_description = 'Proud members of the British Plastics Federation, BioCote® is a worldwide market-leading antimicrobial additives supplier with an established history of over 30 years. Trusted by leading brands and manufacturers of plastic ...', products_services = 'Additives, other, Additive concentrates, Agents biozides, Additives, Coatings, Science and consulting, All product categories', detailed_address = '3, Parade Court, Central Boulevard, Prologis Park', export_content = '> 75%', employees_count = '11 - 30', foundation_year = '1994', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Sports / leisure,, Other industries, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1221;

-- GREAT EASTERN RESINS INDUSTRIAL CO., LTD (ID: 1091)
UPDATE companies SET email = 'flora@greco.com.tw', phone = '+886 4 23587676-683', website = 'https://www.grecoresin.com', company_description = 'Founded in 1955, GRECO specializes in adhesives for footwear and specialty chemicals. Guided by "Quality, Technology, Service," we innovate in water-based PU adhesives, TPU resins, dry film photoresist, and specialty chemicals. As a leading footwear adhesive brand, ...', products_services = 'Thermoplastic elastomers, biobased, All product categories', detailed_address = 'No. 35, 34th Road, Industrial Park Taichung', employees_count = '> 500', foundation_year = 'for its current scale and sustainable operations.', target_groups = 'Chemical industry, Downloads, LFRT Applications DM, Social networks, Visit the exhibitor on the following social networks, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1091;

-- Chrostiki S.A. (ID: 1210)
UPDATE companies SET email = 'sales@chrostiki.gr', phone = '+30 210 6624692', website = 'https://www.chrostiki.com', company_description = 'Chrostiki S.A. is a leading Greek manufacturer of masterbatches, dry color blends, liquid colorants and printing inks, trading also in chemicals for the plastics and printing industries.', products_services = 'Masterbatches, Pastes, Color Masterbatches, Colourants, Calcium carbonate, Printing inks, All product categories', detailed_address = '15-17, Zinonos Street', employees_count = '31 - 100', foundation_year = '1959', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing, Downloads, Chrostiki-brochure-3, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1210;

