-- Batch 15: Companies 141 to 150

-- IMI FABI S.p.A. (ID: 1155)
UPDATE companies SET email = 'info@imifabi.com', phone = '+39 0342 490311', website = 'https://www.imifabi.com', products_services = 'Antiblocking agents, Nucleating agent (see 1.10.81 Nucleating agents), Mineral fillers, Talc, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1155;

-- Nordmann, Rassmann GmbH - Nordmann (ID: 1065)
UPDATE companies SET email = 'info@nordmann.global', phone = '+49 40 3687-0', website = 'https://www.nordmann.global', company_description = 'The company is one of the leading multinational companies in chemical distribution. With subsidiaries in Europe, Asia and North America, Nordmann distributes natural and chemical raw materials, additives and specialty chemicals around the world. As a sales and marketing ...', products_services = 'Acetal homo and copolymers (POM), Bioplastics, biobased, Bioplastics, biologically degradable, PLA (polylactic acid, Polymilchsäure), Bioplastics, Certifications/Standards, Compounds (Polymer blends), Copolyamide TPE-E, TPE-A/PEBA, Copolyester TPE-O, COPE, Ethylene/VAC-copolymers (E/VA), Masterbatches, Polyamid-Copolymer PA 06-66, Polyamide PA 12, Polyamide PA 06, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polycarbonate (PC), Polyethylene PE-HD, Polyethylene PE-LD, Polyethylene PE-LLD, Polyoxymethylne (POM) (s. acetal copolymers), Polypropylene, Polystyrene (PS), Polyvinyl chloride plasticised (PVC-P), Polyvinyl chloride rigid (PVC-U), Thermoplastic urethane blends TPE-U/TPU, Thermoplastic urethane TPE-U/TPU, Polyurethane, biobased, Thermoplastic elastomers, biobased, Polyether block amide, Polyetherester elastomers, PUR-Elastomers, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Thermoplastic PUR-elastomer, SEBS-Blockcopolymer, Epoxy resins (EP), Polyester resins unsaturated (UP), PU elastomers, Vinyl ester resins, Basic products PU, Polyesterpolyols, Polyetherpolyols, Polyurethane casting resins (PUR), Acrylnitril/Butadiene Rubber, Chlorinated polyethylene (CM), Ethylene/propylene terpolymers (EPDM), Fluoro rubber (FPM) (CFM) (MFQ), Silicone rubber (SI), Silicone rubber 02-componemtic, liquid, incl. auxiliaries, Silicone rubber MVQ rigid incl. Auxiliaries, Activators', employees_count = '> 500', foundation_year = '1912', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Agriculture,, Other industries,, Trade, services, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on XING, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1065;

-- WTH Walter Thieme Handel GmbH (ID: 1152)
UPDATE companies SET email = 'info@wthgmbh.de', phone = '+49 4141 52920', website = 'https://www.wthgmbh.de', products_services = 'Chlorinated polyethylene (CPE), Additives, other, Aluminium trihydrate, Antiblocking agents, Antioxidants, Antislip agents, Antistatic agents, Fire protection agents, Dispersing agents, Solid lubricants, Flow auxiliaries, Light stabilisers (s. UV stabilizers), Additives, Metal deactivators, Nucleating agents, Optical brighteners, Pentaerythritol, Smoke density reductioners, Foaming agents, UV stabilizer, Processing auxiliaries, Plasticiser, Aluminium hydroxide, Barium sulfate (barytes, blanc fixe), Microbeads (glass, silicate, hollow and rigid), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1152;

-- ALOXE FRANCE SAS (ID: 1113)
UPDATE companies SET email = 'contact@aloxe.one', phone = '+33 67634763 676347635', website = 'https://WWW.ALOXE.ONE', company_description = 'Aloxe is a pan-European supplier of recycled PET food grade.

Our 3 plants in France, Italy and Poland totalize 100 kt installed capacities.

Our range of products is standardized across plants and we have state-of-the-art assets, from extrusion and decontamination lines to lab ...', products_services = 'Other plastics e.g. Epoxy resins, phenolic resins, polyester resins, melamine resins, urea resins, All product categories', employees_count = '101 - 500', foundation_year = '2020', target_groups = 'Packaging / distribution, Downloads, Aloxe_Brochure_2025, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1113;

-- BRIGHT COLORS SA (ID: 1209)
UPDATE companies SET email = 'info@britecolors.gr', phone = '+30 210 6728490', website = 'https://www.britecolors.gr', company_description = 'BRIGHT COLORS S.A. is a leading masterbatch and compounding specialist based in Greece, with strong export activity across all Europe, the Middle-East and North Africa.', products_services = 'Bioplastics, biobased, Masterbatches, Additive concentrates, Color Masterbatches, Color Blacks (s. 1.10.99 Carbon black), UV stabilizer, All product categories', export_content = 'activity across all Europe, the Middle-East and North Africa.', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing,, Packaging / distribution,, Agriculture,, Other industries, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1209;

-- INDUSTRIE POLIECO - M.P.B. SPA (ID: 1148)
UPDATE companies SET email = 'commerciale@mpb.it', phone = '+39 030 7241521', website = 'https://www.mpb.it', company_description = 'MPB is specialized in the engineering and production of customized plastic compounds.

Thanks to maleic anhydride grafting process, MPB’s polyolefins are intended for:', products_services = 'Compounds (Polymer blends), Polyethylene blends, Polyethylene PE-HD, Polyethylene PE-LD, Polyethylene PE-LLD, Polyethylene PE-MD, Polypropylene, Impact modifier, Maleic resins, One-pack adhesives, Adhesives, Coupling agents, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1148;

-- ELIXANCE SAS (ID: 1108)
UPDATE companies SET email = 'elixance@elixance.com', phone = '+33 2 23101617', website = 'https://www.elixance.com', company_description = 'Elixance, a compound producer in Brittany (France), designs and sells thermoplastic materials tailored to sectors such as packaging, sports & leisure, cosmetics, and more. These materials meet various manufacturing requirements (extrusion, injection, 3D printing, etc.) ...', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, PHA (Polyhydroxyalkanoate), Compounds/Blends, Compounds, natural fiber reinforced, Compounds (Polymer blends), Masterbatches, Ketone resins, Color Masterbatches, Additives, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 25%', employees_count = '31 - 100', foundation_year = '2005', target_groups = 'Plastic product manufacturing,, Chemical industry, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1108;

-- ELSEWEDY POLYMERS JSC (ID: 1199)
UPDATE companies SET email = 'polymers@elsewedy.com', phone = '+20 20 102070777', website = 'https://www.elsewedy-plastic.com', company_description = 'ELSEWEDY POLYMERS, a leading PVC compound and Masterbatch supplier which collaborates with the plastics sector to provide cutting-edge, dependable, and ethical applications. We have made innovation and sustainability the cornerstones of our business over the last few years. ...', products_services = 'Calcium carbonate, All product categories', detailed_address = 'PC.# A6 No. 36/37/38 Industrial Zone A6 Elrobeiky Road, 10th of Ramadan', sales_volume = '> 100 Mill. US $', export_content = 'max. 50%', employees_count = '> 500', foundation_year = '2005', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing,, Vehicle construction / aerospace,, Construction / building and living,, Medical technology / precision engineering / optics, Downloads, El Sewedy Polymers Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1199;

-- KRD Coatings GmbH (ID: 1032)
UPDATE companies SET email = 'info@kasiglas.de', phone = '+49 4152 8086-0', website = 'https://www.kasiglas.de', products_services = 'Polycarbonate (PC), Polymethylmethacrylate (PMMA) and copolymers (s. acrylic glass), Other plastics e.g. Epoxy resins, phenolic resins, polyester resins, melamine resins, urea resins, Parts made by thermoforming, Plastics products and parts for automotive, Plastics products and parts for agriculture, Plastics products and parts for aviation, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Semi finished products of polycarbonate (PC), Coatings, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1032;

-- Exolon Group NV (ID: 1019)
UPDATE companies SET email = 'sales@exolongroup.com', phone = '+32 514 26200', website = 'https://www.exolongroup.com', company_description = 'Exolon Group is a leading supplier of solid and multiwall sheets for various innovative applications. The company develops, produces and distributes polycarbonate sheets, polyester sheets and opaque sheet material made of ...', products_services = 'Products made by extrusion, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for electrical engineering, Plastics products and parts for data appliance, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Semi finished products of polycarbonate (PC), Semi finished products of polyethylene (PE), other and machined semi finished products / Pre-cut parts, Boards and vulcanite boards, Heat insulation plates, All product categories', employees_count = '101 - 500', foundation_year = '2020', target_groups = 'Plastic product manufacturing,, Machinery construction,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Other industries,, Trade, services, Social networks, Visit the exhibitor on the following social networks, Visit us on Instagram, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1019;

