-- Batch 4: Companies 31 to 40

-- IMCD Deutschland GmbH (ID: 1068)
UPDATE companies SET email = 'advanced-materials@imcdgroup.com', phone = '+49 221 77650', website = 'https://www.imcdgroup.com', company_description = 'partners with world-class producers to develop innovative and sustainable solutions for a safer and healthier life.

We distribute high-performance materials to our customers across regions. Our global network of expert teams are eager to ...', products_services = 'PLA (polylactic acid, Polymilchsäure), Copolyamide TPE-E, TPE-A/PEBA, Masterbatches, Polyamide PA 06, Polyamide PA 66, Polyethylene terephthalate (PET), Polyketone, Polyphenylene ether (PPE) modified, Impact modifier, Thermoplastic urethane TPE-U/TPU, Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Epoxy resins (EP), Polyamide, Carbon fibres (CF), Antiblocking agents, Antioxidants, Antislip agents, Antistatic agents, Coupling agents, Carbon black, Impact modifiers, UV stabilizer, Plasticiser, Mould release agents, Barium sulfate (barytes, blanc fixe), Glass beads, Mica, Siloxanes, Cable compounds, Purging compound, All product categories', sales_volume = 's of EUR 4,728 million. IMCD N.V.’s shares are traded at Euronext Amsterdam (symbol: IMCD) and are i', employees_count = '> 500', foundation_year = '1995', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1068;

-- NIKNAM CHEMICALS PVT. LTD. (ID: 1200)
UPDATE companies SET email = 'info@aluminahydrate.com', phone = '+91 93 10014249', website = 'https://www.aluminahydrate.com', company_description = 'The products provided by our company are widely used in Automotive and ...

Established in the year 1992, NIKNAM CHEMICALS PRIVATE LIMITED is engaged in manufacturing, exporting, and supplying of quality environment-friendly FLAME RETARDANT CHEMICALS & FILLERS .', products_services = 'Masterbatches, Polyamide PA 06, Polyamide PA 66, Polycarbonate (PC), Polypropylene, Additives, other, Additive concentrates, Aluminium trihydrate, Antimony trioxide, Fire protection agents, Smoke density reductioners, Aluminium hydroxide, Raw materials, Semi finished products of acryl-nitrile-butadiene (ABS), All product categories', main_website = 'https://www.chinaplasonline.com/eMarketplace/ExhibitorInfo/eng?compid=1048356&Tab=company', detailed_address = 'flame retardant for polypropylene , halogen free flame retardant for nylon , flame retardant for pc/abs , halogen free flame retardant for polypropylene , flame retardant for pa6 , flame retardant for hips , halogen free flame retardant for abs , flame retardant for pbt , halogen-free flame-retardant  , flame retardant for pa66 , halogen free flame retardant for polyamide , flame retardant for nylon6 , flame retardant for pvc , flame retardant for rubber , halogen free flame retardant for pvc , antimony trioxide free flame retardant for pvc ,FLAME RETARDANT ADDITIVES FOR POLYPROPYLENE , flame retardant for compounds /blends , flame retardant for compounds ( polymer blends ), Flame retardant micro-encapsulated red phosphorus powder , flame retardant APP coated with melamine based , flame re', sales_volume = '20 - 100 Mill. US $', export_content = 'ing, and supplying of quality environment-friendly FLAME RETARDANT CHEMICALS & FILLERS .', employees_count = '101 - 500', foundation_year = '1992', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing,, Other industries, Downloads, Halogen-Free Flame Retardants for PP, Halogen-Free Flame Retardants for PA6,Nylon,PA66, FLAME RETARDANT ADDITIVES FOR PP, FLAME RETARDANT ADDITIVES FOR ABS POLYCARBONATE, Flame Retardant Additives for polymers, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1200;

-- Paques Biomaterials BV (ID: 1109)
UPDATE companies SET email = 'info@paquesbiomaterials.nl', website = 'https://www.paquesbiomaterials.nl', company_description = 'Paques Biomaterials  develops a biodegradable alternative to plastic by using organic side streams.', products_services = 'PHA (Polyhydroxyalkanoate), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1109;

-- JIAXING HUAWEN CHEMICAL CO., LTD (ID: 1145)
UPDATE companies SET email = 'liuguizhu@hwsma.com', phone = '+86 573 85627359', website = 'https://www.hwsma.com', company_description = 'Jiaxing Huawen Chemical Co. Ltd., is a professional technology enterprise,

engaged in research, product development, production and supply of styrene and

maleic anhydride copolymer, heat resistant modifier for ABS, maleic anhydride', products_services = 'Coupling agents, All product categories', detailed_address = 'No. 448 West Waihuan Road,', sales_volume = '2,5 - 5 Mill. US $', export_content = 'max. 25%', employees_count = '101 - 500', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing, Downloads, Brochure-Jiaxing Huawen Chemical, Social networks, Visit the exhibitor on the following social networks, Visit us on DouYin, Visit us on facebook, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1145;

-- Daikin Chemical Europe GmbH (ID: 1050)
UPDATE companies SET email = 'sales@daikinchem.de', phone = '+49 211 179225-0', website = 'https://www.daikinchem.de', company_description = 'As a global leader in advanced technologies and manufacturing, Daikin Chemicals specializes in producing fluorochemical and other high-performance materials, playing a key role in providing innovative solutions to industries around the world. Established as part of ...', products_services = 'Bioplastics, biobased, Compounds (Polymer blends), Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Ethylene/tetrafluoroethylene copolymers (E/TFE), Masterbatches, Polyamides blends, Polyaryletherketone (PAEK), Polyetheretherketone (PEEK), Polyetherimide (PEI), Polyphenylene sulfide (PPS), Polytetrafluoroethylene (PTFE), Polytrifluorochloroethylene (PCTFE), Polyvinylidene fluoride (PVDF), Tetrafluoroethylene/perfluoroalkylvinylether copolymers (PFA), Tetrafluoroethylene/perfluoropropylene copolymers (FEP), Fluoro rubber (FPM) (CFM) (MFQ), Additives, other, Flow auxiliaries, Anticorrosive effect, Cleaners, All product categories', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1924', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, ICT,, Energy technology / photovoltaics,, Agriculture, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1050;

-- Plásticos Compuestos S.A. (ID: 1136)
UPDATE companies SET email = 'oficina@kompuestos.com', phone = '+34 93 8639670', website = 'https://www.kompuestos.com', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Bioplastics, cellulose based, Bioplastics, starch based, Compounds/Blends, Compounds (Polymer blends), Granulates, Masterbatches, Additive concentrates, Additives, Calcium carbonate, Siliceous earth, Mineral fillers, Talc, Compounds/Recyclates, All product categories', target_groups = 'around the world. The company maintains a strong commitment to the environment. In this sense, it works in favor of the circular economy of plastic and commits to sustainable innovation to develop biodegradable products and compounds, as well as having a range of products that improve carbon footprint of the final products. Besides, the company also uses advanced plastic recycling technologies., Bookmark, Share profile, Company data, Carrer de L''Orfebreria 3, 08184Palau Solità i Plegamans, Spain, E-mail: oficina@kompuestos.com, Phone: +34 93 8639670, Web:, https://www.kompuestos.com, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1136;

-- Galata Chemicals GmbH (ID: 1217)
UPDATE companies SET email = 'galata.emeaorders@galatachemicals.com', phone = '+49 6206 9570', website = 'https://www.galatachemicals.com', products_services = 'Impact modifier, Additives, other, Antioxidants, Antistatic agents, Biostabilisers, Ca/Zn-Stabilisers, Epoxy plasticiser, Color Masterbatches, Kicker, Additives for electrostatic spray paints, Light stabilisers (s. UV stabilizers), Additives, Matting agent, Secondary plasticisers, Stabilizers, Processing auxiliaries, Plasticiser, Catalysts, Polymerization-catalysts, All product categories', foundation_year = 'on May 1, 2010, Galata Chemicals is a privately he', target_groups = 'like Building and Construction, Packaging, and Automotive from 5 manufacturing facilities on 3 continents. With a focus on innovation and R&D, Galata Chemicals is ready to meet the ever changing requirements of a global marketplace., Bookmark, Share profile, Company data, Chemiestr. 22, 68623Lampertheim, Germany, E-mail: galata.emeaorders@galatachemicals.com, Phone: +49 6206 9570, Web:, https://www.galatachemicals.com, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1217;

-- Best Machine Company Co. Ltd. (ID: 1125)
UPDATE companies SET email = 'info@bestmachine.com.tr', phone = '+90 535 7124359', website = 'https://www.bestmachine.com.tr', company_description = 'Best Machine, an international technology-oriented engineering group company, specialized in technology consulting services and equipments manufacturing.

We have strong technical support. of which 60% are professional technicians.', products_services = 'Extruders, All product categories', export_content = 'ed to more than 5 countries in the world, especially Middle East, which earns us a great reputation.', target_groups = '. Specializing in the technology, projects, and construction management areas. Our comprehensive approach, extensive knowledge and experienced professionals allow us to fully respond to each client’s unique circumstances and requirements.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1125;

-- Terbrack Kunststoff GmbH & Co. KG (ID: 1025)
UPDATE companies SET email = 'info@terbrack.de', phone = '+49 2564 393-0', website = 'https://www.terbrack.de', products_services = 'Products made by extrusion, Parts made by mechanical treating, Parts made by compression moulding, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for mechanical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of polyethylene (PE), Semi finished products of polypropylene (PP), other and machined semi finished products / Pre-cut parts, Parts from standard plastics, Parts from engineering plastics, Parts from high performance thermoplastics, Linings and coatings, All product categories', employees_count = 'one of the leading producers in the field of processing ultra-high and high molecular weight polyeth', foundation_year = 'in 1954 TERBRACK started innovatively and was the ', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1025;

-- ISO-TECH Kunststoff GmbH (ID: 1031)
UPDATE companies SET email = 'verkauf@iso-tech.net', phone = '+49 2561 4290-0', website = 'https://www.iso-tech.net', company_description = 'As one of the leading manufacturers and further processors, ISO-TECH has been producing high-quality thermoplastic products for domestic and foreign customers for more than 30 years. A broad range of production possibilities, a sustainable corporate policy and a distinct ...', products_services = 'Polyamide PA 06, Polyetheretherketone (PEEK), Polyethylene PE-HD, Polyethylene PE-UHMW, Polyoxymethylne (POM) (s. acetal copolymers), Parts made by compression moulding, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Semi finished products of polyethylene (PE), Parts from high performance thermoplastics, Toothed wheels and racks, All product categories', detailed_address = 'As one of the leading manufacturers and further processors, ISO-TECH has been producing high-quality thermoplastic products for domestic and foreign customers for more than 30 years. A broad range of production possibilities, a sustainable corporate policy and a distinct customer orientation characterize our company.', employees_count = '101 - 500', foundation_year = '1990', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1031;

