-- Batch 7: Companies 61 to 70

-- BEGRA Granulate GmbH & Co. KG (ID: 1092)
UPDATE companies SET email = 'granulate@begra.de', phone = '+49 6848 7003-0', website = 'https://www.begra.de', products_services = 'Compounds/Blends, Wood Plastic Composites (WPC), Compounds (Polymer blends), Dry blend, Granulates, Polyvinyl chloride plasticised (PVC-P), Polyvinyl chloride rigid (PVC-U), Polyvinyl chloride expandable, Polyvinyl chloride blends, Polyvinyl chloride copolymers, Thermoplastic elastomers based on PVC, TPE/PVC, All product categories', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1972', target_groups = 'Plastic product manufacturing, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1092;

-- KRAIBURG TPE GmbH & Co. KG (ID: 1064)
UPDATE companies SET email = 'info@kraiburg-tpe.com', phone = '+49 8638 98100', website = 'https://www.kraiburg.tpe.com', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', detailed_address = 'Rubber Street', employees_count = 'worldwide and production sites in Germany, the USA and Malaysia, the company offers a broad product ', foundation_year = 'in 2001 as an independent business unit of the KRA', target_groups = 'as well as for the strictly regulated medical sector.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1064;

-- Guangzhou Meihe Chemical Limited (ID: 1162)
UPDATE companies SET email = 'info@synchemer.com', phone = '+86 20 36685350', website = 'https://www.synchemer.com', company_description = 'SYNCHEMER CO., LIMITED is a High-Tech Enterprise, we are focusing on polymer additives developing, producing and selling. The products are widely used in automotive, construction, electronics, pharmaceutical industries… Benefit from Global and Domestic chemical production ...', products_services = 'Antioxidants, Fire protection agents, Light stabilisers (s. UV stabilizers), Nucleating agents, All product categories', detailed_address = 'Rm1723, Tower 1, Hongding Building No. 565 Yuncheng East Road', export_content = '> 75%', employees_count = '101 - 500', foundation_year = '2012', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture, Downloads, SYNCHEMER CATALOGUE, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1162;

-- K.D. Feddersen Ueberseegesellschaft mbH (ID: 1111)
UPDATE companies SET email = 'polymers@kdfeddersen.com', phone = '+49 40 23507-535', website = 'https://kdfeddersen.global', company_description = 'With more than 75 years of experience, K.D. Feddersen Ueberseegesellschaft specializes in global polymer sourcing - offering the very best polymer, additive, or filler material for our customers.

Our portfolio comprises a range of polymers, additives and filler materials for ...', products_services = 'Acetal homo and copolymers (POM), PLA (polylactic acid, Polymilchsäure), Copolyester TPE-O, COPE, Polyamide PA 06, Polycarbonate (PC), Polyethylene terephthalate (PET), Polyphenylene sulfide (PPS), All product categories', foundation_year = '1949', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Sports / leisure,, Other industries,, Trade, services, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1111;

-- EMS-CHEMIE (Deutschland) Vertriebs GmbH (ID: 1051)
UPDATE companies SET email = 'welcome@de.emsgrivory.com', phone = '+49 6078 7830', website = 'https://www.emsgrivory.com', products_services = 'Barrier plastics, Bioplastics, biobased, Bio-Polyamides, Compounds (Polymer blends), Electrically conductive plastics, Granulates, Optical polymers, Masterbatches, Polyamides blends, Polyamide PA 11, Polyamide PA 12, Polyamide PA 06, Polyamide PA 610, Polyamide PA 612, Polyamide PA 66, Polyamids PA 06-06-T, Polyketone, Polyamide 12-elastomer, Polyether block amide, Other thermoplastic elastomers, Polyamide, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1051;

-- LCY Chemical Corp. (ID: 1078)
UPDATE companies SET email = 'yh.chuang@lcygroup.com', phone = '+886 2 27631611', website = 'https://www.lcygroup.com', company_description = 'With a legacy dating back to 1915, LCY Chemical Corp is committed to reimagining science for a thriving tomorrow. We address human and societal challenges through circular economy solutions and contribute to sustainable industrial practices.', products_services = 'Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), All product categories', detailed_address = '3f, No. 85, Sec. 4, Bade Road', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Construction / building and living,, Medical technology / precision engineering / optics,, Sports / leisure,, Other industries, Downloads, LCY PCMA Catalogue_EN, LCY PP Catalogue__EN, LCY TPE Catalog-EN, LCY PP Health__EN, LCY TPV Catalogue_EN, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1078;

-- Marfran Srl (ID: 1079)
UPDATE companies SET email = 'info@marfran.com', phone = '+39 030 9860511', website = 'https://www.marfran.com', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1079;

-- Plastek UK Ltd (ID: 1034)
UPDATE companies SET email = 'danielle.harkness@plastekgroup.com', phone = '+44 1623 662233', website = 'https://www.plastekgroup.com', company_description = 'The Plastek Group is a trusted global supplier of premium quality injection moulding tools and plastic moulded and blow moulded components serving a wide range of industries including: Homecare, Personal Care, Infant Nutrition, Medical Devices, Plumbing & Heating, Food ...', products_services = 'Parts made by blow moulding, Parts made by injection moulding, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Parts from standard plastics, Parts from engineering plastics, Injection and compression moulds, Blow moulds, All product categories', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 75%', employees_count = '101 - 500', foundation_year = '1999', target_groups = 'Plastic product manufacturing, Downloads, Autumn Newsletter 24, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1034;

-- ASPEN GLOBAL SOLUTIONS SAS (ID: 1094)
UPDATE companies SET email = 'julie@aspen-gs.com', phone = '+33 69002 048765686', website = 'https://www.aspen-gs.fr', products_services = 'PLA (polylactic acid, Polymilchsäure), Polybutyrate (PBAT), Compounds (Polymer blends), Masterbatches, Polyethylene PE-HD, Polyethylene PE-MD, Polypropylene, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1094;

-- Shandong Ruian Biotechnology Co., Ltd. (ID: 1097)
UPDATE companies SET email = 'ruiankeji@ruiangeo.com', phone = '+86 400 0130200', website = 'https://www.ruiangeo.com', company_description = 'Gregeo’s Main Product: PBAT, PBS, TPEE, PCDL, PETG/PCTG and corresponding composite for different applications

A comprehensive service provider specializing in technological innovation for new materials

Ruian Group is a global-operated new materials service ...', products_services = 'Polybutyrate (PBAT), All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Agriculture,, Sports / leisure, Downloads, Brochure-Shandong Ruian Gregeo, Social networks, Visit the exhibitor on the following social networks, Visit us on DouYin, Visit us on LinkedIn, Visit us on WeChat, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1097;

