-- Batch 2: Companies 11 to 20

-- BIOTEC Biologische Naturverpackungen GmbH & Co. KG (ID: 1126)
UPDATE companies SET email = 'inquiries@biotec.de', phone = '+49 2822 9251-0', website = 'https://www.biotec.de', products_services = 'Bioplastics, biologically degradable, All product categories', target_groups = 'such as cosmetics, food, agriculture, pharmaceuticals and others.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1126;

-- Ascom Carbonate and Chemicals Manufacturing (ACCM) (ID: 1018)
UPDATE companies SET email = 'samah.tantawi@accm.com.eg', phone = '+20 202 1224922008', company_description = 'The biggest manufacturer and exporter of ground calcium carbonate in Egypt.

subsidiary of ASEC for Mining, ASCOM began production in 2009 and has since developed a reputation for market success. We provide our clients with ...', products_services = 'Printing inks, Cable compounds, Paints, coatings, Composite materials, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for electro-/household appliance, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Technical Parts from Bulk Molding Compound / Sheet Molding Compound, All product categories', detailed_address = '48, el Nasr Street, new Maadi, Maadi, Cairo, Egypt', sales_volume = '> 100 Mill. US $', export_content = '> 75%', employees_count = '> 500', foundation_year = '2009', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing, Downloads, Company Profile - ACCM, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1018;

-- TRAMACO GmbH (ID: 1161)
UPDATE companies SET email = 'info@tramaco.de', phone = '+49 4101 706-02', website = 'https://www.tramaco.de', company_description = 'Tramaco GmbH specialises in the development, production and sale of innovative, high-quality, high-performance chemical foaming agents, microspheres, adhesion promoters and additives for plastics and rubber processing companies and the coatings industry.', products_services = 'Masterbatches, Pastes, High performance composite materials as semi-finished ware, adhesive films, primer, Chlorinated polypropylene, Additive concentrates, Activators, Ageing stabilizers, Antistatic agents, Lubricants, Coupling agents, Kicker, Light stabilisers (s. UV stabilizers), Nucleating agents, Porosity regulators, Foaming agents, UV stabilizer, Microbeads rigid and hollow, Purging compound, All product categories', employees_count = '31 - 100', foundation_year = 'in 1973. The customer-oriented and internationally', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Electronics / electro technology,, Construction / building and living,, Other industries, Downloads, Chemical Foaming Agents, Adhesion Promoters and Primers, TRAMACO Company Profile, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1161;

-- Kromabatch S.r.l. (ID: 1215)
UPDATE companies SET email = 'info@kromabatch.com', phone = '+39 0293 560123', website = 'https://www.kromabatch.com', company_description = 'Kromabatch is an Italian Company manufacturing high quality color and additive Masterbatches and Combi-batches for the Plastics Market.

The Company boldly starts in 2009, founded by professionals with strong technical background and world class market experience. The ...', products_services = 'Masterbatches, Additive concentrates, Color Masterbatches, All product categories', employees_count = '31 - 100', foundation_year = '2009', target_groups = 'Plastic product manufacturing, Downloads, Brochure Kromabatch 2019-3, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1215;

-- BADGER COLOR CONCENTRATES, INC. (ID: 1211)
UPDATE companies SET email = 'orders@badgercolor.com', phone = '+1 262 2623635710', website = 'https://www.badgercolor.com', company_description = 'BADGER COLOR USA is passionate about partnering with customers to formulate custom solutions for a sustainable future with industry-leading flexibility, responsiveness, and reliability.

Founded in 1998, BADGER COLOR USA is a proud member of ...', products_services = 'Color Masterbatches, All product categories', detailed_address = '1007 Fox Street', employees_count = ', we leverage advanced extrusion, milling, and mixing technologies to deliver flexible, reliable, an', foundation_year = 'in 1998, BADGER COLOR USA is a proud member of the', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1211;

-- Maskom Plastik Sanayi ve Ticaret AŞ (ID: 1216)
UPDATE companies SET email = 'info@maskom.com.tr', phone = '+90 216 5045858', website = 'https://www.maskom.com.tr', company_description = 'Maskom, which set out with the aim of being a brand that exists and produces solutions wherever there is plastic, started its activities in 2007.

Maskom, which moved to Istanbul Gebze facilities in 2009 and Düzce, which carries out its activities today in 2014, became one of ...', products_services = 'Compounds (Polymer blends), Masterbatches, Color Masterbatches, Printing inks, All product categories', foundation_year = 'the Technology Quality Center in 2019 in order to ', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1216;

-- FAINPLAST S.r.l. (ID: 1082)
UPDATE companies SET email = 'info@fainplast.com', phone = '+39 0736 403605', website = 'https://www.fainplast.com', products_services = 'Compounds/Blends, Wood Plastic Composites (WPC), Chlorinated polyethylene (CPE), Compounds (Polymer blends), Granulates, Polyethylene expandable, Polyethylene crosslinkable, Polyethylene blends, Polypropylene, Polyvinyl chloride plasticised (PVC-P), Polyvinyl chloride rigid (PVC-U), Polyvinyl chloride chlorinated (PVC-C), Polyvinyl chloride expandable, Polyvinyl chloride blends, Polyvinyl chloride copolymers, Thermoplastic elastomers based on PVC, TPE/PVC, Olefin based thermoplastic elastomer, TPO, Other thermoplastic elastomers, Thermoset, Ethylene/vinyl acetate foams (EVA), Polyvinyl chloride, Chloroprene rubber (CR), Compounds/Recyclates, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1082;

-- RICO Elastomere Projecting GmbH (ID: 1017)
UPDATE companies SET email = 'office@rico.at', phone = '+43 7242 76460', website = 'https://www.rico.at', company_description = 'RICO is a global solution provider for individual elastomer and thermoplastics projects and offers a full portfolio of services to meet the needs of its customers, including: product development support, prototyping, custom tooling and automation, as well as serial ...', products_services = 'Parts made by injection moulding, Plastics products and parts for automotive, Plastics products and parts for household/consumer, Plastics products and parts for electro-/household appliance, Plastics products and parts for electrical engineering, Plastics products and parts for data appliance, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Plastics products and parts for optics/precision engineering, Sealings/Sealrings, Rubber / plastics combinations, Rubber / plastics / metal combinations, Membranes, Micro parts, Hoses, Valves, Injection and compression moulds, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1017;

-- DIONYMER SAS (ID: 1107)
UPDATE companies SET email = 'thomas.hennebel@dionymer.com', phone = '+33 61450876 614508768', website = 'https://www.dionymer.com', products_services = 'PHA (Polyhydroxyalkanoate), All product categories', detailed_address = '14, Avenue Pey-Berland', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1107;

-- RUTALIA MASTERBATCHES & ADDITIVES EKOGRANULAT C. BURCHERT - EHM AE (ID: 1206)
UPDATE companies SET email = 'rutalia@rutalia.com', phone = '+48 22 4259440', website = 'https://www.rutalia.com', company_description = 'Our company, RUTALIA Masterbatches & Additives, offers the widest range of products on the market for coloring and modifying plastics.

We are a  manufacturer and distributor  of masterbatches and additives for plastics.', products_services = 'Color Masterbatches, Additives, Calcium carbonate, All product categories', employees_count = '5 - 10', foundation_year = '2006', target_groups = 'Chemical industry,, Trade, services, Downloads, KATALOG RUTALIA DE 2025, KATALOG RUTALIA ENG 2025, KATALOG RUTALIA PL 2025, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1206;

