-- Batch 12: Companies 111 to 120

-- ACTEGA GmbH (ID: 1067)
UPDATE companies SET company_description = 'ACTEGA DS GmbH was founded in 1920 under the name of Diersch & Schröder. The company specializes in the manufacture and development of soft elastic plastics in granulate form and sealing compounds for food closures and packaging, TPE materials for medical and ...', products_services = 'Copolyester TPE-O, COPE, Granulates, Styrene/Butadiene-Blockcopolymer, Styrene/butadiene copolymers (SB), Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Olefin based thermoplastic elastomer, TPO, SEBS-Blockcopolymer, TPV-thermoplastic vulcanised material, Other thermoplastic elastomers, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1067;

-- Evonik Industries AG (ID: 1075)
UPDATE companies SET email = 'info@evonik.com', phone = '+49 201 177-01', website = 'https://www.evonik.com', company_description = 'Evonik is a superforce for global industry. Every day, we go beyond the boundaries of chemistry with our combination of innovative strength and leading technological expertise.

Customer-tailored solutions include high-performance polymers such as PA12, PA 612, PA610, ...', products_services = 'Bio-Polyamides, PHA (Polyhydroxyalkanoate), Copolyamide TPE-E, TPE-A/PEBA, Granulates, Masterbatches, Polyamide PA 12, Polyamide PA 610, Polyamide PA 612, Polybutylene terephthalate (PBT), Polyetheretherketone (PEEK), Polyamide 12-elastomer, Polyether block amide, Ethylene/vinyl acetate foams (EVA), Polycarbonate structural foams (PC), Polyethylene foams (PE), Polymethacrylicimide foams (PMI), Polymethylmethacrylate foams (PMMA), Polypropylene-foams (EPP), Polystyrene foams, Copolyamid-adhesives mouldes, Additives, other, Additive concentrates, Antiblocking agents, Antifoam agents, Antislip agents, Antistatic agents, Binders, Biodegradable additives, Dispersing agents, Emulsifiers, Color Masterbatches, Flow auxiliaries, Lubricants, Coupling agents, Additives, Matting agent, Nucleating agents, Foamstabilisers, Impact modifiers, Thixotropic agents, Release agents, Processing auxiliaries, Thickeners, Crosslinking agents, Precipitated silices, Pyrogenic silica, Silanes, Siloxanes, Products made by extrusion, Parts made by foaming, Semi-finished parts/products made from fibre-reinforced plastics, All product categories', detailed_address = 'Smart Effects in Plastics: Innovative silica and silane technologies are transforming the plastics industry by enhancing performance, processing, and sustainability. SPHERILEX® 30 AB and 60 AB offer anti-blocking effects for high-clarity films, ensuring transparency and easy handling. SIPERNAT® D 17 improves flow and prevents caking in powder systems, while SIPERNAT® 380 supports dispersion and consistency in formulations. For silane crosslinking, Dynasylan® SILFIN 301 and ready-to-use Dynasylan® SILFIN mixtures provide reliable solutions for HFFR compounds and cable production. Dynasylan® HYDROSIL offers reactive, water-based silane hydrolysates, and Dynasylan® Oligomers outperform standard monomers in adhesion and durability.', target_groups = 'AG, Evonik is a superforce for global industry. Every day, we go beyond the boundaries of chemistry with our combination of innovative strength and leading technological expertise.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1075;

-- ADEKA Polymer Additives Europe SAS (ID: 1159)
UPDATE companies SET email = 'contact@adeka-pa.eu', phone = '+33 3 68750530', website = 'https://www.adeka-pa.eu', company_description = 'ADEKA Corporation is a speciality chemicals, electronic, life sciences company with a worldwide turnover in excess of € 2 billion per year.

The polymer additives division forms a strategic and integral business for ADEKA. We are a global company with polymer additives ...', products_services = 'Additives, other, Additive concentrates, Ageing stabilizers, Amine sterically hindered, Antioxidants, Antistatic agents, Ba/Cd-Stabilisers, Fire protection agents, Ca/Zn-Stabilisers, Solid lubricants, Light stabilisers (s. UV stabilizers), Metal deactivators, Nucleating agents, Smoke density reductioners, Foaming agents, Stabilizers, UV stabilizer, Plasticiser, All product categories', sales_volume = '> 100 Mill. US $', export_content = 'max. 75%', employees_count = '> 500', foundation_year = '1917', target_groups = 'Plastic product manufacturing,, Chemical industry,, Other industries, Downloads, ADEKA_Company_Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1159;

-- PALMAROLE AG (ID: 1164)
UPDATE companies SET email = 'contact@palmarole.ch', phone = '+41 61 2810376', website = 'https://www.palmarole.com', products_services = 'Nucleating agents, All product categories', target_groups = 'since the company’s establishment in 1982.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1164;

-- ADVANCE BIO MATERIAL CO PVT LTD (ID: 1098)
UPDATE companies SET email = 'info@advancebioplast.com', phone = '+91 80 80209351', website = 'https://www.advancebioplast.com', company_description = 'Advance Bio Material P. Ltd. is an innovator and is dedicated to developing high-performance Bioplastics. We serve a global customer base with design and technical support. Our India operation has offices in Mumbai, Ahmedabad, Chennai, and Delhi, covering ...', products_services = 'Bookmark, Visit our stand Hall 7, level 2 / E10 to learn all about our products.', detailed_address = '525, Avior, Nirmal Galaxy, LBS Road, Mulund-West', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 10%', employees_count = '31 - 100', foundation_year = '2012', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Other industries,, Trade, services, Downloads, ABM-Brochure-Raw material, compostable-flexible-packaging, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on WhatsApp, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1098;

-- BENVIC SAS (ID: 1066)
UPDATE companies SET email = 'contact@benvic.com', phone = '+33 3 80467300', website = 'https://www.benvic.com', company_description = 'Benvic is a leading international polymer compounder with over 60 years of technical expertise in the formulation and manufacture of PVC compounds, engineering plastics, biobased plastics, compostables and medical applications.', products_services = 'Bioplastics, biobased, Compounds/Blends, Compounds (Polymer blends), Electrically conductive plastics, Granulates, Masterbatches, Polypropylene, Polyvinyl chloride plasticised (PVC-P), Polyvinyl chloride rigid (PVC-U), Polyvinyl chloride chlorinated (PVC-C), Record compounds, Thermoplastic urethane blends TPE-U/TPU, Thermoplastic elastomers, biobased, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Thermoplastic elastomers based on PVC, TPE/PVC, Polypropylene, Polyvinyl chloride, Embedding compounds, Electrical insulation compounds, Cable compounds, Purging compound, Parts made by blow moulding, Products made by extrusion, Parts from engineering plastics, Parts from high performance thermoplastics, Compounds/Recyclates, All product categories', detailed_address = '57, avenue de Tavaux', target_groups = 'Plastic product manufacturing,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Other industries, Downloads, Benvic_Corporate brochue, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1066;

-- ALBIS Distribution GmbH & Co. KG (ID: 1030)
UPDATE companies SET email = 'info@albis.com', phone = '+49 40 781050', website = 'https://www.albis.com', company_description = 'ALBIS is one of the world''s leading distributors of standard polymers, engineering plastics, and thermoplastic elastomers. With technical know-how, a strong distribution network and a strong commitment to finding the best solution, ALBIS as an independent distributor ...', products_services = 'Acetal homo and copolymers (POM), Acrylic glass (s. PMMA), Acrylonitrile/butadiene/styrene polymerblends, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Bioplastics, biobased, Compounds/Blends, Bioplastics, Certifications/Standards, Cellulose propionate (CP), Compounds (Polymer blends), Electrically conductive plastics, Granulates, Optical polymers, Masterbatches, Polyamides blends, Polyamide PA 06, Polyamide PA 66, Polyaryletherketone (PAEK), Polycarbonate (PC), Polyetheretherketone (PEEK), Polyethersulfone (PES, PESU), Polyethylene PE-HD, Polyethylene PE-LLD, Polymethylmethacrylate (PMMA) and copolymers (s. acrylic glass), Polypropylene, Polystyrene (PS), Polysulfone (PSU), Polyvinylidene fluoride (PVDF), Styrene/butadiene copolymers (SB), Styrene/acrylonitrile copolymers (SAN), M-ABS, Thermoplastic urethane TPE-U/TPU, Thermoplastic elastomers, biobased, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Acrylonitrile-butadiene-styrene, acrylonitrile-styrene-acrylate, styrene-acrylonitrile copolymer, Polyamide, Other thermoplastics, e.g. POM, PC, PBT, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for electro-/household appliance, Plastics products and parts for medical engineering, Plastics products and parts for transport/packaging, All product categories', employees_count = '> 500', target_groups = 'Chemical industry,, Machinery construction,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Sports / leisure,, Other industries, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1030;

-- MOCOM Compounds GmbH & Co. KG (ID: 1058)
UPDATE companies SET email = 'info@mocom.eu', phone = '+49 40 781050', website = 'https://www.mocom.eu', company_description = 'MOCOM Compounds GmbH & Co. KG, with its headquarters in Hamburg, Germany, is a global compounder of thermoplastic polymers and recycling specialist. The company offers the plastics processing industry a comprehensive product range of high-performance plastics as well as ...', products_services = 'Acetal homo and copolymers (POM), Acrylonitrile/butadiene/styrene polymerblends, Bioplastics, biobased, Cellulose acetate butyrate (CAB), Cellulose propionate (CP), Electrically conductive plastics, Granulates, Masterbatches, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polycarbonate (PC), Polycarbonate blends, Polymethylmethacrylate (PMMA) and copolymers (s. acrylic glass), Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene sulfide (PPS), Polypropylene, Polystyrene (PS), Styrene/acrylonitrile copolymers (SAN), Thermoplastic urethane TPE-U/TPU, TPV-thermoplastic vulcanised material, Polypropylene, Polyamide, Other thermoplastics, e.g. POM, PC, PBT, All product categories', employees_count = '> 500', target_groups = 'Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Medical technology / precision engineering / optics,, Sports / leisure,, Other industries, Downloads, PDF file, PDF file, PDF file, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1058;

-- RTP Company (ID: 1085)
UPDATE companies SET email = 'rtp@rtpcompany.com', phone = '+1 507 4546900', website = 'https://www.rtpcompany.com', products_services = 'Masterbatches, Polyamide PA 06, Polyamide PA 66, Polycarbonate (PC), Polyetheretherketone (PEEK), Polyethersulfone (PES, PESU), Polyphenylene sulfide (PPS), Polypropylene, Olefin based thermoplastic elastomer, TPO, Other thermoplastic elastomers, Semi finished products of acryl-nitrile-butadiene (ABS), All product categories', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1982', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Other industries, Downloads, RTP Company Brochure, RTPco-Color Brochure_web, RTPco_Conductive Brochure, RTPco_Flame Retardant Brochure_web, RTP Co_Long Glass Fiber Brochure_web, RTPco_Structural Brochure_web, RTP Co_Thermoplastic Elastomers Brochure_web, RTP Co_Wear and Friction Resistant Compounds Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1085;

-- Isik Plastik A.S. (ID: 1021)
UPDATE companies SET email = 'info@isikplastik.com.tr', phone = '+90 262 7512235', website = 'https://www.isikplastik.com.tr', products_services = 'Acrylic glass (s. PMMA), Products made by extrusion, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for agriculture, Plastics products and parts for aviation, Plastics products and parts for furniture appliances, Plastics products and parts for transport/packaging, Semi finished products of polycarbonate (PC), Semi finished products of polyethylene (PE), Semi finished products of polymethylmethacrylate (PMMA), Semi finished products of polypropylene (PP), Semi finished products of polystyrene (PS), Cointainers, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1021;

