-- Batch 13: Companies 121 to 130

-- AYTEK SOGUTMA IC VE DIS TIC. A.S. (ID: 1117)
UPDATE companies SET email = 'info@aytekchillers.com', phone = '+90 212 5491199', website = 'https://www.aytekchillers.com', company_description = 'With over 40 years of industry experience, Aytek Soğutma (also known as Itech) is a leading provider of advanced cooling solutions, specializing in water chilling systems for both industrial ...', products_services = 'Heating and cooling units, All product categories', foundation_year = '1980', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Machinery construction,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Agriculture, Downloads, Cooling UNITS Catalog, Soğutma Kataloğu, FREETECH DRY COOLER ENG, WATER COOLED UNITS, MASTERTECH SCREW TYPE ENG, NOVATECH SCROLL TYPE ENG, BLASTAIRTECH, ECOTECH TR-ENG HYBRID CHILLER, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1117;

-- M J PIGMENT AND ADDITIVES PVT. LTD. (ID: 1219)
UPDATE companies SET email = 'jaswant@mjpa.co.in', phone = '+91 91 9829204368', website = 'https://WWW.MJPA.CO.IN', company_description = 'MJPA is a leading Manufacturer of Plastic Masterbatchs and a trusted trader of a wide range of materials, including Pigments, Dyes, Polymers, Advanced polymers, Resins, Calcium fillers, Talc, Moisture Absorbers, Titanium dioxide, Carbon black, Waxes, and other additives.', products_services = 'Colour pigments, All product categories', target_groups = 'such as plastics, PVC, Rubber, Textiles, Coatings, Inks, and Footwear. Committed to quality and innovation, MJPA ensures that all our offerings meet stringent industry standards, providing reliable solutions that enhance performance and sustainability. With a dedicated team and a focus on customer satisfaction, we continue to expand our global reach and impact., Bookmark, Share profile, Company data, H-425a, Riico Industrial Area Rajasthan, 301707Khushkhera (Bhiwadi), India, E-mail: jaswant@mjpa.co.in, Phone: +91 91 9829204368, Web:, https://WWW.MJPA.CO.IN, Social networks, Visit the exhibitor on the following social networks, Visit us on WhatsApp, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1219;

-- Weber & Schaer GmbH & Co. KG (ID: 1087)
UPDATE companies SET email = 'office@weber-schaer.com', phone = '+49 40 30902-0', website = 'https://www.weber-schaer.com', products_services = 'Acrylonitrile/styrene/acrylic ester copolymers (ASA), Chlorinated polyethylene (CPE), Compounds (Polymer blends), Granulates, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, TPV-thermoplastic vulcanised material, Acrylnitril/Butadiene Rubber, Brominebutyl Rubber BIIR, Butadiene rubber (BR), Butyl rubber (IIR), Chlorinebutyl Rubber, Chlorinated polyethylene (CM), Chloroprene rubber (CR), Cis-01,04-polybutadiene (BR), Cis-01,04-polyisoprene (IR), Ethylene/propylene terpolymers (EPDM), Fluoro rubber (FPM) (CFM) (MFQ), Natural rubber, Nitrile rubber, Styrene/butadiene rubber (SBR), Aramide fibres, Carbon fibres (CF), Dispersion adhesives, Ageing stabilizers, Carbon black, Vulcanisation accelerator, Precipitated silices, Peroxides, All product categories', detailed_address = 'We have been in the natural rubber business for over 140 years and with this experience we are the competent supplier. Thanks to our long-standing sales partnership with the Korean Kumho Group, we have an excellent quality portfolio in the field of synthetic rubbers. This is supplemented by further partnerships. A broad range of rubber chemicals and fillers rounds off our offering for the elastomer industry.', employees_count = 'are distinguished by their long service with the company and have excellent specialist knowledge. Th', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1087;

-- AGRANA Stärke GmbH (ID: 1060)
UPDATE companies SET email = 'info.staerke@agrana.com', phone = '+43 121 137', website = 'https://www.agrana.com', company_description = 'AGRANA is an international Austrian industrial company that refines agricultural raw materials into high-quality products for the processing industry. With many years of experience in starch processing, AGRANA develops sustainable and innovative solutions, including ...', products_services = 'Bioplastics, biobased, All product categories', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Construction / building and living,, Other industries, Downloads, PDF file, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1060;

-- MURTFELDT GmbH & Co. KG (ID: 1038)
UPDATE companies SET email = 'info@murtfeldt.de', phone = '+49 231 42577980', website = 'https://www.murdotec.de', products_services = 'Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Semi finished products of polyethylene (PE), Screws, All product categories', employees_count = 'put their knowledge and experience at the service of our customers.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1038;

-- TITK - Thüringisches Institut für Textil- und Kunststoff-Forschung e.V. (ID: 1044)
UPDATE companies SET email = 'info@titk.de', phone = '+49 3672 379-0', website = 'https://www.titk.de', company_description = 'About TITK – Thuringian Institute for Textile and Plastics Research Rudolstadt e.V.:

TITK is one of the leading private materials research institutes for polymer-based functional and construction materials. As an industry-oriented institution with a modern technology park, ...', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Cellulose fibres (Viscose-, Acetate fibres), Polyamide fibres, Hot melt adhesives, Plastics products and parts for automotive, Plastics products and parts for medical engineering, Plastics products and parts for transport/packaging, Semi-finished parts/products made from fibre-reinforced plastics, Compounds/Recyclates, Rubber / plastics combinations, Parts of industrial laminates, Science and consulting, All product categories', employees_count = ', also includes the subsidiaries OMPG mbH and smartpolymer GmbH. As an industry-oriented research in', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1044;

-- Covestro Deutschland AG (ID: 1049)
UPDATE companies SET email = 'info@covestro.com', phone = '+49 214 60092000', website = 'https://www.covestro.com', company_description = 'We offer a broad range of products and services for varying markets, demands and industries. That’s why we group our portfolio by business specifics and customer needs.

There are two big segments: ‘Performance Materials’ and ...', products_services = 'Polyurethane, bio-based, Polycarbonate (PC), Polycarbonate blends, Thermoplastic urethane TPE-U/TPU, All product categories', detailed_address = 'We offer a broad range of products and services for varying markets, demands and industries. That’s why we group our portfolio by business specifics and customer needs.', employees_count = '> 500', foundation_year = '2015', target_groups = 'Plastic product manufacturing,, Chemical industry,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Sports / leisure,, Other industries, Social networks, Visit the exhibitor on the following social networks, Visit us on Instagram, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1049;

-- ITENE Packaging, Transport & Logistics Research Center (ID: 1135)
UPDATE companies SET email = 'info@itene.com', phone = '+34 96 1820000', website = 'https://www.itene.com', company_description = 'ITENE is a leading research and technology center specialized in packaging, transport, and logistics. For over 30 years, we have supported companies worldwide through R&D projects, testing services, technical assistance, and training, providing technological solutions ...', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Bioplastics, Certifications/Standards, Reinforcing materials, Polyethylene, high density, Polypropylene, Polystyrene, Biodegradable additives, Science and consulting, All product categories', target_groups = 'such as food and beverage, cosmetics, chemicals, pharmaceuticals, logistics, distribution, recycling, and raw materials.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1135;

-- ARGUS Additive Plastics GmbH (ID: 1153)
UPDATE companies SET email = 'mail@argus-additive.de', phone = '+49 2951 9909-0', website = 'https://www.argus-additive.com', company_description = 'FOUNDED in 1994, the renowned family business ARGUS has remained true to its principles for more than 25 years: to continuously produce forward-looking masterbatches with innovative methods that set the highest quality standards both at national and ...', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Compounds (Polymer blends), Masterbatches, Additive concentrates, Antiblocking agents, Antioxidants, Antislip agents, Antistatic agents, Fire protection agents, Color Masterbatches, Flow auxiliaries, Lubricants, Light stabilisers (s. UV stabilizers), Matting agent, Nucleating agents, Optical brighteners, Processing auxiliaries, Purging compound, All product categories', foundation_year = '1994', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1153;

-- SHL Advantec AG (ID: 1170)
UPDATE companies SET email = 'info@shl-advantec.com', phone = '+41 41 3680000', website = 'https://www.shl-advantec.com', company_description = 'SHL Advantec is a global provider of high-performance, turnkey manufacturing and packaging equipment and solutions for medical devices, and other highly demanding applications in the automotive, aerospace, construction industries and more. We specialize in advanced ...', products_services = 'Moulds, Assembly systems, All product categories', employees_count = '> 500', foundation_year = '2025', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Medical technology / precision engineering / optics, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1170;

