-- Batch 3: Companies 21 to 30

-- NUREL, S.A. (ID: 1081)
UPDATE companies SET email = 'marketing_nurel@samca.com', phone = '+34 976 465579', website = 'https://www.nurel.com', products_services = 'Barrier plastics, Bioplastics, biologically degradable, Bioplastics, starch based, Compounds/Blends, Compounds (Polymer blends), Copolyamide TPE-E, TPE-A/PEBA, Polyamides blends, Polyamid-Copolymer PA 06-66, Polyamide PA 12, Polyamide PA 06, Polyamide PA 612, Polyamide PA 06-03-T, Polyamide PA 66, Polyamids PA 06-06-T, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polyethylene terephthalate (PET), Polypropylene, Polyvinyl alcohol (PVAL), Other thermoplastic elastomers, All product categories', sales_volume = '> 100 Mill. US $', export_content = 'max. 75%', employees_count = '101 - 500', foundation_year = '1968', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1081;

-- Büchler Reinli + Spitzli AG (ID: 1129)
UPDATE companies SET email = 'm.voegtle@brsflawil.ch', phone = '+41 71 3941300', website = 'https://www.brsflawil.ch', products_services = 'Injection and compression moulds, Moulds, Subcontracting, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '31 - 100', foundation_year = '1966', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1129;

-- TECNI-PLASPER SLU (ID: 1203)
UPDATE companies SET email = 'plasper@plasper.com', phone = '+34 93 8468369', website = 'https://www.plasper.com', company_description = 'Since 1983, Plasper has been a trusted partner in the plastics industry, offering two key lines of solutions.

✅ Our Recycling Line produces high-quality recycled polymers, including P-PVC compounds and HFFR, as well as providing re-compounding services to help ...', products_services = 'Compounds (Polymer blends), Masterbatches, Polyvinyl chloride plasticised (PVC-P), Processing auxiliaries, Calcium carbonate, Talc, Subcontracting, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1203;

-- Plastiblow S.r.l. (ID: 1101)
UPDATE companies SET email = 'plastiblow@plastiblow.it', phone = '+39 02 48012102', website = 'https://www.plastiblow.it', company_description = 'Plastiblow is worldwide recognized as a qualified producer of extrusion blow molding machines. Its range of models cover a variety of applications from bottles to canisters blown from different thermoplastic materials and with capacities up to 30 liters. In 2001 Plastiblow ...', products_services = 'Extrusion blow moulding machines, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1101;

-- Milliken Europe bv (ID: 1150)
UPDATE companies SET email = 'eurochem@milliken.com', phone = '+32 265 11-00', website = 'https://www.milliken.com', company_description = 'Milliken & Company is a global manufacturing leader whose focus on materials science delivers tomorrow’s breakthroughs today. From industry-leading molecules to sustainable innovations, Milliken creates products that enhance people’s lives and ...', products_services = 'Polypropylene, Additives, other, Additive concentrates, Color Masterbatches, Colourants, Dyestuffs, soluble, Functional pigments, Nucleating agent (see 1.10.81 Nucleating agents), Light stabilisers (s. UV stabilizers), Additives, Nucleating agents, UV stabilizer, Flow control agents, Crosslinking agents, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1150;

-- Celanese Sales Germany GmbH (ID: 1048)
UPDATE companies SET email = 'marcomminfo@celanese.com', phone = '+49 69 450090', website = 'https://www.celanese.com', company_description = 'Our Vision at Celanese is to improve the world and everyday life through our people, chemistry and innovation. So, it follows that the Celanese Foundation is aligned with this vision and is dedicated to improving the quality of life for people around the world.', products_services = 'Acetal homo and copolymers (POM), Bioplastics, biobased, Polyesters, Bioplastics, cellulose based, Cellulose acetate, secondary (CA), Compounds (Polymer blends), Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Polyamid-Copolymer PA 06-66, Polyamid-Copolymer PA 66-06, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polyethylene PE-UHMW, Polyethylen PE-UHMW cellular, Polyethylene terephthalate (PET), Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene sulfide (PPS), Polypropylene, Thermoplastic urethane blends TPE-U/TPU, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), TPV-thermoplastic vulcanised material, All product categories', detailed_address = 'Celanese Sales Germany GmbH', employees_count = 'together with local partners to create meaningful, sustained change.', foundation_year = 'is aligned with this vision and is dedicated to im', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1048;

-- Joss Elastomers & Chemicals B.V. (ID: 1076)
UPDATE companies SET email = 'info@joss.nl', phone = '+31 72 51570-64', website = 'https://www.joss.nl', products_services = 'Chlorinated polyethylene (CPE), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Brominebutyl Rubber BIIR, Butyl rubber (IIR), Chloroprene rubber (CR), Chlorosulfonated polyethylene (CSM), Ethylene/propylene terpolymers (EPDM), Natural rubber, Styrene/butadiene rubber (SBR), Carbon black, Vulcanising agents, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1076;

-- Kuraray Europe GmbH (ID: 1077)
UPDATE companies SET email = 'k-show@kuraray.com', phone = '+49 69 30585300', website = 'https://www.kuraray.eu', company_description = 'Kuraray Europe GmbH was founded in 1991. The company is headquartered in Hattersheim near Frankfurt am Main and generated annual sales of 1.1 billion euros in 2024. Across Germany, more than 820 ...

Exclusive K Show Landing Page: https://go.kuraray.com/k2025', products_services = 'Ethylene/vinyl alcohol copolymers (E/VAL), Polyvinyl alcohol (PVAL), Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Polyvinyl butyrals, All product categories', main_website = 'https://go.kuraray.com/k2025', employees_count = '> 500', foundation_year = '1926', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology, Downloads, PDF file, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1077;

-- Bruker BioSpin GmbH & Co. KG (ID: 1127)
UPDATE companies SET email = 'info@bruker.com', phone = '+49 7243 7695-000', website = 'https://www.bruker.com', company_description = 'The Bruker BioSpin Group develops, manufactures, and distributes advanced scientific instruments based on magnetic resonance and preclinical imaging technologies. This includes leading NMR, EPR, and TD-NMR spectrometers, as well as imaging systems utilizing MRI, PET, SPECT, ...', products_services = 'Measuring and test equipment for rheological properties, Measuring equipment for melt tempeature, Measuring equipment for moisture content, Plastic types identification equipment, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1127;

-- Symplast Kimya San. ve Tic. A.S. (ID: 1086)
UPDATE companies SET email = 'info@symplast.de', phone = '+90 232 3257171', website = 'https://symplast.com.tr', company_description = 'Symplast is a globally operating compounder of thermoplastic elastomers (TPE) and thermoplastic vulcanizates (TPV), founded in 2013 in Izmir—where our headquarters and production facilities are still located today. Our European operations are managed from our branch in ...', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Olefin based thermoplastic elastomer, TPO, TPV-thermoplastic vulcanised material, All product categories', detailed_address = 'Thanks to the location of our production site at an international seaport and our broad network of global distribution partners, we ensure fast and reliable worldwide delivery.', employees_count = '101 - 500', foundation_year = '2013', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Other industries, Downloads, Symflex® F Series - Flame-retardant TPE, Symflex® HS Series - Excellent compression set, Symflex® Recycled Series - TPE with recycled content, Symflex® Impact Modifier Series - enhanced impact resistance, Symflex® TPV Series, Symflex® Y Series - TPE for 2K injection molding, Symplast General Catalogue English, Symplast Gesamtkatalog Deutsch, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1086;

