-- Batch 16: Companies 151 to 160

-- High Grade Industries (India) Pvt.Ltd (ID: 1208)
UPDATE companies SET email = 'ishan@highgrade.in', phone = '+91 22 40775076', website = 'https://www.highgrade.in', company_description = 'Leading the Future of Polymer Additives, Masterbatches & Compounds

Founded in 2000 by Mr. G. S. Kohli, High Grade Industries (India) Pvt. Ltd. has grown into a trusted name in the field of Plastics Compounding, ...', products_services = 'Compounds (Polymer blends), Masterbatches, Additive concentrates, Antioxidants, Color Masterbatches, Additives, Optical brighteners, UV stabilizer, All product categories', detailed_address = 'A/510-513, Crystal Plaza, New Link Road, Andheri West', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '2001', target_groups = 'Plastic product manufacturing, Downloads, HighGrade Brochure - Masterbatch Solutions for Packaging - August 2024, Masterbatches for PE Films, High Grade Corporate Brochure 2024, HighADD products for BOPP/CPP films, HighPET products for PET applications, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1208;

-- PLASTORE SRL (ID: 1071)
UPDATE companies SET email = 'commerciale@plastore.it', phone = '+39 0425 1666273', website = 'https://www.plastore.it', company_description = 'A 30 years experience in the plastics market enables our people to always give you the right solution:', products_services = 'Acetal homo and copolymers (POM), Acrylonitrile/butadiene/styrene polymerblends, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Polyamide PA 46, Polyamide PA 06, Polybutylene terephthalate (PBT), Polycarbonate (PC), Polyetheretherketone (PEEK), Polyetherimide (PEI), Polyethylene PE-HD, Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene ether (PPE) modified, Polyphenylene sulfide (PPS), Polypropylene, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1071;

-- B4Plastics BVBA (ID: 1062)
UPDATE companies SET email = 'lt@b4plastics.com', phone = '+32 479 729753', website = 'https://www.b4plastics.com', company_description = 'At B4Plastics we create, produce, sell and license renewable and/or recyclable/biodegradable materials for all industries.

We specialize in creating materials with customizable lifespans, allowing you to decide when your product will naturally break down, leaving no ...', products_services = 'Bioplastics, biobased, All product categories', sales_volume = '1 - 2,5 Mill. US $', employees_count = '11 - 30', foundation_year = '2018', target_groups = 'Rubber manufacturing / processing,, Vehicle construction / aerospace,, Construction / building and living,, Agriculture,, Sports / leisure,, Other industries, Downloads, About_B4PLASTICS, B4P_Flyer_CYCLAN, B4P_FORTAN_FORTAMID, B4P_HUMICUR, B4P_LICENSING HOUSE, B4P_RD, B4P_TRIGGERPLASTICS, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1062;

-- ELASTEVER SAS (ID: 1083)
UPDATE companies SET email = 'contact@elastever.com', phone = '+33 2 52352612', website = 'https://www.elastever.com', company_description = 'Elastever develops thermoplastic elastomer (TPE) formulations from recycled raw materials, in particular recycled thermoset elastomer powders. These recycled raw materials come in particular from the end-of-life tyre and shoe industries.', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), Olefin based thermoplastic elastomer, TPO, TPV-thermoplastic vulcanised material, Other thermoplastic elastomers, Other thermoplastics, e.g. POM, PC, PBT, All product categories', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing,, Vehicle construction / aerospace,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Other industries, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1083;

-- NIPPON TALC CO., LTD. (ID: 1166)
UPDATE companies SET email = 'baba@nippon-talc.co.jp', phone = '+81 6 65672735', website = 'https://www.nippon-talc.co.jp', company_description = 'Founded in 1934, Nippon Talc Co., Ltd. has supported global industries for over 90 years as a specialized manufacturer of mineral fillers. Our high-quality talc and other mineral-based fillers are used in plastics, rubber, coatings, adhesives, electronic materials, ...', products_services = 'KUROTALC Keep it Black, Add the Benefit, talc powder, carbon alternative, TKD Scallop Powder, Sustainable Calcium carbonate from Scallop Shells, CaCO3, recycle, Nano Ace Series – Ultrafine Talc, nucleating agent(PLA, PP, PBS, PA6/PA66, PBT, PET (cPET)) ,3D printing, Halogen-Free Flame Retardant – Magnesium Hydroxide, Brucite, MDH, MgOH2, for PE, PP, PVC, and EVA., Anti-caking agent for fertilizer, Talc, bulk blend fertilizer, chemical fertilizer, Revolutionizing Adhesive Performance with Submicron Talc, silicon, epoxy, polyimide, adhesive, polyimide-based FCCL', detailed_address = 'Another breakthrough is the TKD Scallop Powder Series, representing our commitment to circular economy and CO₂ reduction. Derived from scallop shells and produced without the traditional calcination process, TKD achieves significant CO₂ savings. With a mild pH of 9.3 compared to 13.4 for calcined products, it improves workplace safety, while odor and chlorine are removed for clean handling. With more than 96% purity in CaCO₃, TKD provides superior bending modulus and toughness compared to limestone-derived fillers. It offers broad application potential in plastics, rubber, coatings, detergents, and deodorants.', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 25%', employees_count = '101 - 500', foundation_year = '1934', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Electronics / electro technology,, Construction / building and living,, Agriculture, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1166;

-- Barnes Group Acquisition GmbH (ID: 1121)
UPDATE companies SET email = 'lhaack@onebarnes.com', phone = '+49 7663 609-0', products_services = 'Injection and compression moulds, Hotrunner systems, Moulds, All product categories', employees_count = 'in Europe, the USA and Asia, is one of the leading suppliers in the industry. Since 2013, männer has', foundation_year = 'in 1965 and, with over 500 employees in Europe, th', target_groups = '., Bookmark, Share profile, Company data, Unter Gereuth 9-11, 79353Bahlingen, Germany, E-mail: lhaack@onebarnes.com, Phone: +49 7663 609-0, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1121;

-- IMERYS SA (ID: 1163)
UPDATE companies SET website = 'https://www.imerys.com', company_description = 'Imerys is the world leader in mineral-based specialties, offering high value-added solutions to many different industries, ranging from process manufacturing to consumer goods.

We engineer minerals that make excellent reinforcing fillers and nucleating agents in ...', products_services = 'Reclaimed material, Antiblocking agents, Nucleating agents, Carbon black, Calcium carbonate, Graphite, Kaolin, Mineral fillers, Talc, Wollastonite, Mica, All product categories', employees_count = '> 500', foundation_year = '1880', target_groups = ', ranging from process manufacturing to consumer goods.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1163;

-- GKG Goldmann Kunststoffe GmbH & Co. KG (ID: 1174)
UPDATE companies SET email = 'info@gold-mann.de', phone = '+49 521 93278-0', website = 'https://www.gold-mann.de', products_services = 'Acrylonitrile/butadiene/styrene copolymers, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Compounds/Blends, Compounds (Polymer blends), Polyamides blends, Polyamid-Copolymer PA 06-66, Polyamid-Copolymer PA 66-06, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polymethylmethacrylate (PMMA) and copolymers (s. acrylic glass), Polypropylene, Styrene/acrylonitrile copolymers (SAN), Antimony trioxide, Fire protection agents, Smoke density reductioners, Polymerization-catalysts, All product categories', detailed_address = 'With our own branch office in China and through our partners within the PlusChem Group, we have an extensive and established network. Our capabilities are broad and range from product sourcing and auditing of supplier factories to the launch of European products in international markets.', export_content = 'merchant. At the same time, we enable science graduates to start their careers directly after gradua', employees_count = 'Through the targeted selection, promotion and training of our colleagues, we ensure a high level of ', foundation_year = ', the Goldmann Group today consists of S. Goldmann', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1174;

-- Supreme Petrochem Ltd. (ID: 1165)
UPDATE companies SET email = 'kb_mathew@spl.co.in', phone = '+91 22 67091900', website = 'https://www.supremepetrochem.com', company_description = 'Supreme Petrochem Ltd. is promoted jointly by The Supreme Industries Ltd., India’s largest plastics processor, and the well diversified R. Raheja Investments Pvt Ltd.

The Supreme Industries Limited, founded in 1942 has been relevant with the ...', products_services = 'Acrylonitrile/butadiene/styrene copolymers, Compounds (Polymer blends), Masterbatches, Polystyrene (PS), Polystyrene expandable (EPS), Color Masterbatches, Nucleating agents, All product categories', detailed_address = '2007 started India’s first and only integrated plant of XPS (Extruded Polystyrene) Insulation foam boards to support and promote Green Building movement in India and are registered with IGBC and GRIHA.', export_content = 's have grown considerably too. Today the company proudly serves customers in more than 100 countries', foundation_year = 'in 1942 has been relevant with the changing times ', target_groups = 'Ltd., India’s largest plastics processor, and the well diversified R. Raheja Investments Pvt Ltd. , The Supreme Industries Limited, founded in 1942 has been relevant with the changing times and continues to be a household name solely because of the core values that they uphold., Raheja Group has multifarious business interests covering cement, ceramic tiles, automotive batteries, cable TV, retail superstores, construction, etc.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1165;

-- Rajiv Plastics Pvt. Ltd. (ID: 1096)
UPDATE companies SET email = 'information@rajivplastics.com', phone = '+91 22 66929701', website = 'https://www.rajivplastics.com', company_description = 'Rajiv Plastics is one of Asia’s leading Color & Additive Masterbatch and Compound manufacturers. Incorporated in 1978, we are an ISO 9001:2015 certified company with world class manufacturing facilities. We export to more than 60 countries worldwide. We use the ...', products_services = 'Bioplastics, biobased, PLA (polylactic acid, Polymilchsäure), Polybutyrate (PBAT), Bioplastics, starch based, Compounds/Blends, Compounds (Polymer blends), Masterbatches, Biodegradable additives, Color Masterbatches, Pigment Black, Pigment Black Preparations, Foaming agents, Purging compound, All product categories', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1978', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure,, Trade, services, Downloads, Rajiv Plastics Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1096;

