-- Batch 5: Companies 41 to 50

-- Envalior BV (ID: 1093)
UPDATE companies SET email = 'monique.os-van@envalior.com', phone = '+31 6 30503410', website = 'https://envalior.com', company_description = 'At Envalior, we believe that our customers deserve only the highest quality products, services and support. Our commitment to quality is simple: zero defects. To achieve this, we follow a Total Quality Program that focuses on continuous improvement in everything we do. ...', products_services = 'Bio-Polyamides, Compounds (Polymer blends), Polyamide PA 46, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polyethylene terephthalate (PET), Polyphenylene sulfide (PPS), Thermoplastic elastomers based on PVC, TPE/PVC, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1093;

-- MP3 S.R.L. (ID: 1037)
UPDATE companies SET email = 'info@ilpa-mp3.com', phone = '+39 051 6715811', website = 'https://www.mp3extrusion.com', products_services = 'Products made by extrusion, Parts made by thermoforming, Embossing, Plastics products and parts for automotive, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of acryl-nitrile-butadiene (ABS), Semi finished products of polypropylene (PP), Semi finished products of polystyrene (PS), All product categories', export_content = 'In 2012, MP3 acquired 100% control of AMP Recycling, which boasts a long tradition in the field of p', foundation_year = 'in Italy in 1978. In 2016 it became MP3 Srl.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1037;

-- Ampacet Europe SA (ID: 1115)
UPDATE companies SET email = 'marketing.europe@ampacet.com', phone = '+352 29 20991', website = 'https://www.ampacet.com', company_description = 'Founded in 1937, Ampacet Corporation is a leading global masterbatch supplier committed to designing innovative custom colors, high performance additive solutions, multipurpose whites and blacks as well as sustainable masterbatches.', products_services = 'Masterbatches, Color Masterbatches, All product categories', foundation_year = ', Ampacet continues to drive innovation in the pla', target_groups = 'across the plastics value chain.,  Headquartered in Tarrytown, New York, Ampacet employs over 2,000 professionals worldwide and operates 20 manufacturing sites, including technical and color development centers in 17 countries throughout the Americas, Asia, and Europe. In Europe, the company runs seven production plants, with its regional headquarters located in Luxembourg.,  Ampacet is deeply committed to sustainability, consistently developing environmentally responsible solutions to address both environmental and societal challenges. Its growing portfolio of sustainable products reflects its proactive role in promoting circular economy practices and reducing environmental impact.,  Demonstrating its focus on specialized markets, Ampacet has recently introduced ELTech™ masterbatches, eng', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1115;

-- Shree Radhekrishna Extrutech Pvt. Ltd. (ID: 1143)
UPDATE companies SET email = 'exports@radhekrishnaexports.com', phone = '+91 79 9924204506', website = 'https://www.extrutech.in', company_description = 'Extrutech is a globally trusted manufacturer and exporter of advanced plastic extrusion machinery, specializing in screw & barrel systems, complete extrusion lines, and both upstream & downstream equipment. With over 32+ years of ...', products_services = 'Extruders, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1992', target_groups = 'Plastic product manufacturing, Downloads, Extrutech Digital Brochure, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1143;

-- TEPE KIMYA SAN VE TIC A.S. (ID: 1105)
UPDATE companies SET email = 'info@tepekimya.com', phone = '+90 216 5931920', website = 'https://www.tepekimya.com.tr', products_services = 'Additives, other, All product categories', export_content = 'ing its products to 60+ countries all across globe and developing its products to provide innovative', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1105;

-- Plastika Kritis S.A. Global Colors Group (ID: 1095)
UPDATE companies SET email = 'info@plastikakritis.com', phone = '+30 2810 308500', website = 'https://www.plastikakritis.com', company_description = 'Global Colors - part of the Plastika Kritis Group - is one of Europe’s largest masterbatch producers, delivering high-performance color, additive, white, and black masterbatches to the plastics industry worldwide. With production facilities in Greece, Romania, ...', products_services = 'Bioplastics, biologically degradable, Polybutyrate (PBAT), Compounds/Blends, Compounds (Polymer blends), Masterbatches, Additive concentrates, Antioxidants, Antistatic agents, Color Masterbatches, Light stabilisers (s. UV stabilizers), Additives, Carbon black, Cable compounds, Purging compound, All product categories', detailed_address = 'P. Street Iraklion Industrial Area', export_content = 's to more than 50 countries, Global Colors delivers consistent quality, cutting-edge technology, and', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1095;

-- traceless materials GmbH (ID: 1144)
UPDATE companies SET email = 'contact@traceless.eu', phone = '+49 170 5488213', website = 'https://www.traceless.eu', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, All product categories', foundation_year = 'bioeconomy startup based in Hamburg, Germany.  Wit', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1144;

-- GM Color Sp. z o.o. (ID: 1212)
UPDATE companies SET email = 'office@gmcolor.pl', phone = '+48 52 51535-35', website = 'https://www.gmcolor.pl', company_description = 'GM Color is family business, fully with Polish capital, operating on the domestic and European markets since 2004. We specialize in the production of high-quality color masterbatches and additives as well a compounds and regranulates. We focus on diversity, which is why our ...', products_services = 'Color Masterbatches, Additives, All product categories', employees_count = '101 - 500', foundation_year = '2004', target_groups = 'Plastic product manufacturing, Downloads, GM Color Folder EN 2024, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1212;

-- iPB Printing BV (ID: 1104)
UPDATE companies SET email = 'info@ipbprinting.com', phone = '+31 497 621212', website = 'https://www.ipbprinting.com', company_description = 'iPB Printing specializes in the production of In Mould Labels (IML) and Flexible Packaging. For various applications, we offer you the ideal solution, with a focus on quality and processability.', products_services = 'Printing, All product categories', sales_volume = '5 - 20 Mill. US $', employees_count = '31 - 100', target_groups = 'Packaging / distribution, Downloads, General_IML_US, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1104;

-- Peerless Plastics & Coatings ltd (ID: 1169)
UPDATE companies SET email = 'pstamp@peerless-coatings.co.uk', phone = '+44 1842 750333', website = 'https://www.peerless-coatings.co.uk', company_description = 'Striving for excellence in all that we do, we offer flexible, bespoke,  protective hard coating  solutions to all our customers the world over.

Offering a complete chain solution from design, research & ...', employees_count = '31 - 100', target_groups = 'Plastic product manufacturing, Downloads, PEERLESS-Brochure June 2022-v2, Peerless – PRODUCTS HandOut A4 - 4pp – SINGLE PAGES, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on X, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1169;

