-- Batch 9: Companies 81 to 90

-- Apex-Desco Machine Company Corp. (ID: 1116)
UPDATE companies SET email = 'email@apexmachine.com', phone = '+1 954 5661572', website = 'https://www.apexmachine.com', company_description = 'Based in Florida-USA, this fourth generation family driven company is active in diverse manufacturing ...

Apex offers an unmatched level of experience and expertise in designing-engineering customized part handling and marking/decorating solutions for 3-D packaging products.', products_services = 'Printing equipment for plastic and rubber products, All product categories', foundation_year = '1903', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1116;

-- BASF SE (ID: 1043)
UPDATE companies SET email = 'global.info@basf.com', phone = '+49 621 60-0', website = 'https://www.basf.com', company_description = 'About BASF at K 2025: Welcome to #OurPlasticsJourney!

#OurPlasticsJourney continues in 2025 at K! Join us at our booth in Hall 5, C21/D21 and discover how to start your green transformation. At BASF, we look at the entire lifecycle of plastics with Make, Use and Recycle. ...', products_services = 'Acetal homo and copolymers (POM), Bioplastics, biobased, Bioplastics, biologically degradable, Bio-Polyamides, Polyurethane, bio-based, Bioplastics, Certifications/Standards, Compounds (Polymer blends), Granulates, Polyamides blends, Polyamid-Copolymer PA 06-66, Polyamid-Copolymer PA 66-06, Polyamide PA 06, Polyamide PA 610, Polyamide PA 66, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polyethersulfone (PES, PESU), Polyoxymethylne (POM) (s. acetal copolymers), Polystyrene (PS), Polystyrene expandable (EPS), Polysulfone (PSU), Polyurethane thermoplastic (PUR), Thermoplastic urethane blends TPE-U/TPU, Thermoplastic urethane TPE-U/TPU, Thermoplastic elastomers, biobased, PUR-Elastomers, Thermoplastic PUR-elastomer, Thermoset, PU elastomers, Melamine/formaldehyde foams (MF), Polystyrene foams, Polyurethane casting resins (PUR), Polyurethane casting resins rigid structural foams-RIMsystems, Polyurethane casting resins semi-rigid structural foams-RIM-systems, Polyurethane casting resins rigid foams-systems, Polyurethane casting resins semi-rigid foams-systems, Polyurethane casting resins flexible foams-systems, Polyurethane casting prepolymer binder resins, Polystyrene, Expanded polystyrene, Additives, other, Additive concentrates, Ageing stabilizers, Amine sterically hindered, Antioxidants, Antistatic agents, Fire protection agents, Light stabilisers (s. UV stabilizers), Additives, Metal deactivators, Optical brighteners, Phthalate plasticisers, Stabilizers', employees_count = 'in the BASF Group contribute to the success of our customers in nearly all sectors and almost every ', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1043;

-- Omya Performance Polymer Distribution AG (ID: 1040)
UPDATE companies SET email = 'info@omya.com', phone = '+41 62 7892639', website = 'https://www.omya.com', company_description = 'OPPD is a global leader with more than 60 years of experience, innovation and expertise in the distribution and application development of thermoplastic polymers and elastomers.

Our team of highly experienced sales people are able to meet your requirements and exceed your ...', products_services = 'Acetal homo and copolymers (POM), Acetal polymerblends, Acrylic glass (s. PMMA), Acrylonitrile/butadiene/styrene polymerblends, Acrylonitrile/butadiene/styrene copolymers, Acrylonitrile/styrene/acrylic ester copolymerblends, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Barrier plastics, Bioplastics, biobased, Bioplastics, biologically degradable, Bio-Polyamides, Polyethylene terephthalate, biobased (Bio-PET), Polyethylene, biobased (Bio-PE), PLA (polylactic acid, Polymilchsäure), Polyesters, Polyurethane, bio-based, Bioplastics, cellulose based, Bioplastics, starch based, Bioplastics, lignin based, Bioplastics based on proteins, Compounds/Blends, Compounds, natural fiber reinforced, Bioplastics, Certifications/Standards, Compounds (Polymer blends), Copolyamide TPE-E, TPE-A/PEBA, Copolyester TPE-O, COPE, Cycloolefine Polymers, Dry blend, Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Ethylene/Acrylic acid/Butylacrylate E-AA-BA, Ethylene/ethylene acrylate copolymers (E/EA), Ethylene/methylene acrylate copolymers (E/MA), Ethylene/VAC-copolymers (E/VA), Ionomers, Optical polymers, Light-collecting plastics, Masterbatches, Polyamides blends, Polyamid-Copolymer PA 06-66, Polyamid-Copolymer PA 66-06, Polyamide PA 11, Polyamide PA 12, Polyamide PA 46, Polyamide PA 06, Polyamide PA 610, Polyamide PA 612, Polyamide PA 06-03-T, Polyamide PA 66, Polyamids PA 06-06-T, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, ', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1040;

-- QolorTech BV (ID: 1137)
UPDATE companies SET email = 'sales@qolortech.nl', phone = '+31 578 569666', website = 'https://www.qolortech.nl', company_description = 'The best of both worlds! Combining Budenheim''s innovative additives and QolorTech''s processing and formulation capabilities strengthens our competence in the market by offering a broad portfolio of solutions which synergistically complement each other ...', products_services = 'Masterbatches, Antioxidants, Antistatic agents, Biodegradable additives, Fire protection agents, Color Masterbatches, Additives, Nucleating agents, Foaming agents, UV stabilizer, All product categories', detailed_address = 'The best of both worlds! Combining Budenheim''s innovative additives and QolorTech''s processing and formulation capabilities strengthens our competence in the market by offering a broad portfolio of solutions which synergistically complement each other in diverse polymer applications. With QolorTech and Budenheim under one roof, we cooperate as close partners towards one common goal - a safe and sustainable future.', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Agriculture,, Other industries, Downloads, Budenheim QolorTech Polymers (brochure), QolorTech ReQolor (Flyer - Budenheim), QolorTech ReQreate (Flyer), QolorTech NIR (Flyer), QolorTech Bio (Flyer Budenheim), Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1137;

-- Kaneka Belgium N.V. (ID: 1026)
UPDATE companies SET email = 'kaneka.K2025@kaneka.be', phone = '+32 14 257800', website = 'https://www.kaneka.be', company_description = 'Through world-class science and technology, Kaneka is providing an array of solutions to diverse markets worldwide. Aligned with the global strategy, the Kaneka Group focuses its activities on four business domains: Materials, Quality of Life, Health Care, and Nutrition.', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, Impact modifier, Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Silane-resins, Polyethylene foams (PE), Polypropylene-foams (EPP), Binders, Adhesives, Matting agent, Impact modifiers, Processing auxiliaries, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for electro-/household appliance, Plastics products and parts for agriculture, Plastics products and parts for aviation, Plastics products and parts for transport/packaging, All product categories', detailed_address = '“Building a sustainable future for people and planet through the power of chemistry,”', target_groups = 'Plastic product manufacturing,, Chemical industry,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Sports / leisure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1026;

-- European Bioplastics e.V. (ID: 1110)
UPDATE companies SET email = 'info@european-bioplastics.org', phone = '+49 30 28482-350', website = 'https://www.european-bioplastics.org', products_services = 'Trade associations, All product categories', foundation_year = 'in this industry, bioplastics MAGAZINE, is more th', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1110;

-- Frilvam S.p.a. (ID: 1142)
UPDATE companies SET email = 'frilvam@frilvam.com', phone = '+39 0331 587171', website = 'https://www.frilvam.com', products_services = 'Masterbatches, All product categories', foundation_year = 'in the first years after World War II, Frilvam, ba', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1142;

-- ADVANCED & FUNCTIONAL TECHNOLOGIES FOR BIOCOMPOSITES S.L. (ID: 1059)
UPDATE companies SET email = 'info@adbioplastics.com', phone = '+34 96 820000', website = 'https://www.adbioplastics.com', company_description = 'ADBioplastics is a Spanish company specialised in the development and commercialisation of advanced additives and bioplastics.

Our PLA-Premium bioplastic improves elongation at break (mechanical properties) by up to 70%, achieving a version of PLA Premium, that is, less ...', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, PLA (polylactic acid, Polymilchsäure), Compounds (Polymer blends), Biodegradable additives, Impact modifiers, All product categories', main_website = 'https://www.europapress.es/', foundation_year = '2016', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Agriculture,, Other industries, Downloads, ADBioplastics'' general brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on Instagram, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1059;

-- Delta Tecnic, S.A. (ID: 1198)
UPDATE companies SET email = 'deltatec@deltatecnic.com', phone = '+34 93 8674284', website = 'https://www.deltatecnic.com', products_services = 'Masterbatches, All product categories', detailed_address = 'Pol. Ind. Moli de Les Planes C/ Rec. Moli de les Planes s/n', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1198;

-- ASAHI KASEI EUROPE GmbH (ID: 1061)
UPDATE companies SET email = 'plastics@asahi-kasei.eu', phone = '+49 211 33992000', website = 'https://www.asahi-kasei.eu', company_description = 'With more than 50,000 employees worldwide, the Japanese technology company Asahi Kasei contributes to a sustainable society by providing solutions to the world''s challenges through its three business sectors of Material, Homes, and Health Care. Its Material sector includes ...', products_services = 'Acetal homo and copolymers (POM), Acrylic glass (s. PMMA), Bioplastics, biobased, Compounds (Polymer blends), Polyamide PA 610, Polyamide PA 612, Polyamide PA 66, Polyphenylene ether (PPE) modified, Polypropylene, Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Polyphenylene ether structural foams (PPE), Cellulose fibres, All product categories', detailed_address = 'With more than 50,000 employees worldwide, the Japanese technology company Asahi Kasei contributes to a sustainable society by providing solutions to the world''s challenges through its three business sectors of Material, Homes, and Health Care. Its Material sector includes a wide array of products from technical foams, engineering plastics, battery separators and biodegradable textiles to recycling technologies and electronic devices for a broad range of industries.', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1922', target_groups = 'Chemical industry, Downloads, General brochure 2025, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1061;

