-- Batch 2: Companies 4-13

UPDATE companies SET email = 'info@pleiger-kunststoff.de', phone = '+49 2324 3980', website = 'https://www.pleiger-kunststoff.de', products_services = 'Polyurethane casting resins flexible foams-systems, Linings and coatings, Parts made by mechanical treating, Parts made by compression moulding, Parts made by rotation moulding, Parts made by foaming, Parts made by injection moulding, Plastics products and parts for plant building, Plastics products and parts for building applications, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for furniture appliances, Plastics products and parts for transport/packaging, Semi finished products of polyurethane (PUR), other and machined semi finished products / Pre-cut parts, Parts from standard plastics, Parts from engineering plastics, Apparatus and parts, Armatures and parts, Sealings/Sealrings, Bellows, expansible, Conveyor belts, Casings and cabinets, Rubber hollow springs, Rubber / plastics / metal combinations, Bogie wheels and runners, Packing rings, Membranes, Parts for pumps, Suction cups, Valves, Fibreglass-reinforced plastic parts, Rollers and roller coatings, All product categories', employees_count = 'have the appropriate know-how in the areas of design, formulation development, tool and mold constru', foundation_year = '1953', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1016;


UPDATE companies SET email = 'info@stearinerie-dubois.fr', phone = '+331461007320 1 4610073', website = 'https://www.stearinerie-dubois.com', company_description = 'Stéarinerie Dubois offers a wide range of bio-based and synthetic additives for the rubber and polymer industry.', products_services = 'Adipates, Biodegradable additives, Lubricants, Stearic acid, Release agents, Waxes, Plasticiser, All product categories', employees_count = '101 - 500', foundation_year = '1820', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Vehicle construction / aerospace,, Sports / leisure,, Other industries,, Universities, technical colleges, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1138;


UPDATE companies SET email = 'masterbatchinfo@kandui.in', phone = '+91 22 62673500', website = 'https://www.kandui.in', company_description = 'Kandui Industries is a globally trusted and leading manufacturer of masterbatches with an extensive reach across the globe.

Kandui Industries Pvt. Ltd. established since 2006 is one of the leading manufacturer & exporter of Masterbatches in India with an annual ...', products_services = 'Compounds/Blends, Compounds (Polymer blends), Masterbatches, Polyester fibres, Polypropylene fibres, Antiblocking agents, Antimony trioxide, Antioxidants, Antifoam agents, Antislip agents, Antistatic agents, Fire protection agents, Colour pigments, Color Masterbatches, Colourants, Color Blacks (s. 1.10.99 Carbon black), Shiner, Light stabilisers (s. UV stabilizers), Additives, Nucleating agents, Optical brighteners, Impact modifiers, UV stabilizer, Calcium carbonate, Talc, All product categories', detailed_address = '2006 is one of the leading manufacturer & exporter of Masterbatches in India with an annual manufacturing capacity of 50000MT & plans to expand further to 60000MT in the upcoming years.', export_content = 'er of Masterbatches in India with an annual manufacturing capacity of 50000MT & plans to expand furt', foundation_year = 'since 2006 is one of the leading manufacturer & ex', target_groups = 'Plastic product manufacturing,, Packaging / distribution, Downloads, Kandui-Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on WhatsApp, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1156;

UPDATE companies SET email = 'info@solinatra.com', phone = '+44 1603 551224', website = 'https://www.solinatra.com', company_description = 'Solinatra is a next-generation biopolymer that delivers the performance of traditional plastics without leaving a trace. Made from renewable, responsibly sourced materials and engineered to be 100% free from fossil-fuel plastics, ...', products_services = 'Bioplastics, biobased, All product categories', detailed_address = 'Abbey Farm Commercial Park Southwell Road, Horsham st Faith', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1039;


UPDATE companies SET email = 'alberto@baracco.biz', phone = '+39 0425 760041', website = 'https://www.baracco.biz', company_description = 'Baracco S.r.l. is a highly specialized company engaged in the engineering, development, manufacturing, marketing, and global distribution of systems, spare parts, and accessories for plastic ...', products_services = 'Pelletizers, All product categories', foundation_year = 's of his technical knowledge. From 1993 to 2017, h', target_groups = 'Machinery construction, Downloads, BARACCO_BROCHURE 2023_ENGLISH (1), My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1120;


UPDATE companies SET email = 'julia.jiang@mytpe.com', phone = '+86 139 25852800', website = 'https://www.ekgtpe.com', products_services = 'Thermoplastic elastomers, biobased, All product categories', detailed_address = 'No.6, Xingye Road, Longkeng, Dongkeng', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1090;


UPDATE companies SET email = 'linda.bibus@thor.com', phone = '+49 6232 636-0', website = 'https://www.thor.com', company_description = 'You may not realize it, but THOR''s extraordinary products are probably already part of your life. Whether they preserve your dish soap or laundry detergent, protect your furniture or clothing in case of fire, or enhance your moisturizers and shampoos, THOR''s innovative ...', products_services = 'Masterbatches, Additives, other, Fire protection agents, Additives, All product categories', detailed_address = '15 countries worldwide (Australia, Brazil, China, France, Germany, India, Italy, Japan, Korea, Malaysia, Mexico, Singapore, South Africa, Spain, Sweden, Turkey, UK, USA), so you are never far from a THOR expert. Whether you need biocidal or disinfectant agents, ingredients for personal care products, or flame-retardant chemicals, we are always close by!', employees_count = '> 500', foundation_year = '1959', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture,, Sports / leisure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1220;


UPDATE companies SET email = 'inquiries@biotec.de', phone = '+49 2822 9251-0', website = 'https://www.biotec.de', products_services = 'Bioplastics, biologically degradable, All product categories', target_groups = 'such as cosmetics, food, agriculture, pharmaceuticals and others.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1126;


UPDATE companies SET email = 'samah.tantawi@accm.com.eg', phone = '+20 202 1224922008', company_description = 'The biggest manufacturer and exporter of ground calcium carbonate in Egypt.

subsidiary of ASEC for Mining, ASCOM began production in 2009 and has since developed a reputation for market success. We provide our clients with ...', products_services = 'Printing inks, Cable compounds, Paints, coatings, Composite materials, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for electro-/household appliance, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Technical Parts from Bulk Molding Compound / Sheet Molding Compound, All product categories', detailed_address = '48, el Nasr Street, new Maadi, Maadi, Cairo, Egypt', sales_volume = '> 100 Mill. US $', export_content = '> 75%', employees_count = '> 500', foundation_year = '2009', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing, Downloads, Company Profile - ACCM, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1018;

UPDATE companies SET email = 'info@tramaco.de', phone = '+49 4101 706-02', website = 'https://www.tramaco.de', company_description = 'Tramaco GmbH specialises in the development, production and sale of innovative, high-quality, high-performance chemical foaming agents, microspheres, adhesion promoters and additives for plastics and rubber processing companies and the coatings industry.', products_services = 'Masterbatches, Pastes, High performance composite materials as semi-finished ware, adhesive films, primer, Chlorinated polypropylene, Additive concentrates, Activators, Ageing stabilizers, Antistatic agents, Lubricants, Coupling agents, Kicker, Light stabilisers (s. UV stabilizers), Nucleating agents, Porosity regulators, Foaming agents, UV stabilizer, Microbeads rigid and hollow, Purging compound, All product categories', employees_count = '31 - 100', foundation_year = 'in 1973. The customer-oriented and internationally', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Electronics / electro technology,, Construction / building and living,, Other industries, Downloads, Chemical Foaming Agents, Adhesion Promoters and Primers, TRAMACO Company Profile, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1161;


