-- Batch 11: Companies 101 to 110

-- LORENZ Kunststofftechnik GmbH (ID: 1033)
UPDATE companies SET email = 'info@lomix.de', phone = '+49 5407 8322-0', website = 'https://www.lomix.de', company_description = 'As a medium-sized company, we have been your partner in the development and manufacture of customer-specific plastic products for more than 50 years. We are a European leader in the development and production of glass fiber reinforced composites, SMC and BMC – thanks to our ...', products_services = 'Compounds, natural fiber reinforced, Bulk moulding compounds (BMC), Dough moulding compounds (DMC), Thermoset, Casting resins, Sheet moulding compounds (SMC) (UP-SMC), Polyester resin moulding compounds, Prepregs, SMC (sheet moulding compounds), Other plastics e.g. Epoxy resins, phenolic resins, polyester resins, melamine resins, urea resins, Parts made by compression moulding, Parts made by injection moulding, Plastics products and parts for automotive, Plastics products and parts for household/consumer, Plastics products and parts for electro-/household appliance, Plastics products and parts for electrical engineering, Plastics products and parts for agriculture, Technical Parts from Bulk Molding Compound / Sheet Molding Compound, All product categories', foundation_year = '1966', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Machinery construction,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture,, Other industries, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1033;

-- Pöppelmann Kunststoff-Technik GmbH & Co. KG (ID: 1022)
UPDATE companies SET email = 'k-tech@poeppelmann.com', phone = '+49 4442 982-620', website = 'https://www.poeppelmann.com', products_services = 'Parts made by injection moulding, Parts made by thermoforming, Welding, Plastics products and parts for plant building, Plastics products and parts for automotive, Plastics products and parts for electrical engineering, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Fastenings, Casings and cabinets, Rubber / plastics combinations, Laboratory equipment- technical parts, Parts for pumps, Fibreglass-reinforced plastic parts, All product categories', employees_count = '> 500', foundation_year = '1949', target_groups = ', as well as the surface technology and fittings industries., Bookmark, Share profile, Company data, Postfach 11 60, 49378 undefined, Hermann-Staudinger-Str. 1, 49393Lohne, Germany, E-mail: k-tech@poeppelmann.com, Phone: +49 4442 982-620, Web:, https://www.poeppelmann.com, Number of employees > 500, Foundation 1949, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1022;

-- Gema Elektro Plastik ve Elektronik San. Dis Tic. A.S. (ID: 1134)
UPDATE companies SET email = 'info@gemapolimer.com', phone = '+90 232 2515041', website = 'https://www.gemapolimer.com', company_description = 'Gema Polimer is among the leading companies in manufacturing Masterbatch & Compounds with a production capacity of 100.000 tons. With experience of more than 40 years in the sector manufacturing the highest quality products in an ever evolving marketplace, our ...', products_services = 'Bioplastics, biobased, Compounds/Blends, Compounds (Polymer blends), Masterbatches, Polyamides blends, Polyethylene blends, Polypropylene, All product categories', export_content = '> 75%', employees_count = '101 - 500', foundation_year = '1996', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture,, Other industries,, Trade, services, Downloads, gema-catalog, gema-products, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on X, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1134;

-- JJ Plastalloy Pvt. Ltd. (ID: 1214)
UPDATE companies SET email = 'dhirendra@jjplastalloy.com', phone = '+91 22 35127082', website = 'https://www.jjplastalloy.com', company_description = 'JJ Plastalloy specializes in manufacturing and exporting high-quality masterbatches and polymer compounds tailored for diverse industries, including automotive, packaging, agriculture, and textiles. With over 29 years of expertise, the company provides innovative solutions ...', products_services = 'Polyesters, Compounds/Blends, Compounds (Polymer blends), Granulates, Masterbatches, Color Masterbatches, Impact modifiers, UV stabilizer, White pigments, Calcium carbonate, Glass beads, All product categories', detailed_address = '29 years of expertise, the company provides innovative solutions for color, additive, and specialty requirements, enhancing product performance and sustainability. Recognized as a 2-star export house by the Government of India, JJ Plastalloy exports to over 40 countries, delivering exceptional quality and fostering global partnerships in the plastic industry.', export_content = 'ing high-quality masterbatches and polymer compounds tailored for diverse industries, including auto', target_groups = ', including automotive, packaging, agriculture, and textiles. With over 29 years of expertise, the company provides innovative solutions for color, additive, and specialty requirements, enhancing product performance and sustainability. Recognized as a 2-star export house by the Government of India, JJ Plastalloy exports to over 40 countries, delivering exceptional quality and fostering global partnerships in the plastic industry., Bookmark, Share profile, Company data, A2, Badshah Bagh Colony Maldahiya, 221002Varanasi Uttar Pradesh, India, E-mail: dhirendra@jjplastalloy.com, Phone: +91 22 35127082, Web:, https://www.jjplastalloy.com, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on YouTube,', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1214;

-- Shenyang Ketong Plastic Co. ,LTD (ID: 1149)
UPDATE companies SET email = 'ketong@syketong.com', phone = '+86 24 89362427', website = 'https://www.syketong.com', company_description = 'Shenyang Keton Plastics Co.,Ltd.is a high-tech company   specializing   in   the   research,  production and sales of toughening agents, compatibilizers and functional ...', products_services = 'Ethylene/VAC-copolymers (E/VA), All product categories', detailed_address = 'No. 11-1, 11-2, Hongbin Road, Yuhong District', employees_count = '101 - 500', foundation_year = '2003', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1149;

-- COLORFIX Itamaster ind de Masterbatches LTDA (ID: 1205)
UPDATE companies SET email = 'francielo@colorfix.com.br', phone = '+55 41 3675-5300', website = 'https://www.colorfix.com.br', company_description = 'Colorfix Masterbatches has been innovating and developing color concentrates and/or additives since 1990, promoting improvements in both products and processes for its customers.

Its headquarters are located in Colombo, in the metropolitan region of Curitiba, Paraná, ...', products_services = 'Compounds/Blends, Bioplastics, Certifications/Standards, Compounds (Polymer blends), Masterbatches, All product categories', main_website = 'https://www.k-online.com/vis/v1/en/search?_query=colorfix', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 10%', employees_count = '101 - 500', foundation_year = '1990', target_groups = 'Plastic product manufacturing,, Chemical industry, Downloads, Complete Marble Line Catalog, Social networks, Visit the exhibitor on the following social networks, Visit us on Instagram, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1205;

-- BBA Innova AG (ID: 1122)
UPDATE companies SET email = 'cooler@bba-innova.com', phone = '+41 62 8369966', website = 'https://www.bba-innova.com', company_description = 'Continuous cooling and continous cooling belt systems and additional equipment to cool and solidify viscous materials. Steel belt coolers, drum coolers and special equipment for the plastic-, chemical-, pharmaceutical-, powder coating and toner industry and special ...', products_services = 'Apparatus and parts, All product categories', export_content = '> 75%', employees_count = '11 - 30', foundation_year = '2005', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing, Downloads, PDF file, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1122;

-- ELASTRON KIMYA SAN. VE TIC. A.Ş. Elastron TPE (ID: 1063)
UPDATE companies SET email = 'elastron@elastron.com', phone = '+90 262 6430001', website = 'https://www.elastron.com', company_description = 'Elastron is a global thermoplastic elastomers (TPE) producing company located in Turkey, has offices in North America, China, Germany and exports to over 50 countries.', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', export_content = 's to over 50 countries.', employees_count = 'and strong background. Besides high-tech laboratory equipment, our R&D Centre supports the market re', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1063;

-- Alok Masterbatches Pvt. Ltd. (ID: 1204)
UPDATE companies SET email = 'info@alokindustries.com', phone = '+91 11 41612244', website = 'https://www.alokmasterbatches.com', company_description = 'ALOK Masterbatches (ALOK), a family owned, and family managed enterprise is recognised as India’s most trusted masterbatch manufacturer. Known for co-creating innovative, reliable and high-quality solutions for their customers, ALOK has put innovation and ...', products_services = 'Compounds (Polymer blends), Masterbatches, Additive concentrates, Color Masterbatches, All product categories', detailed_address = '110020New Delhi', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1993', target_groups = 'Plastic product manufacturing,, Chemical industry,, Other industries, Downloads, ALOK_ATIC Catalog - Updates 2025, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1204;

-- Torimex Group Sp z o.o. (ID: 1173)
UPDATE companies SET email = 'kundendienst@torimex.pl', phone = '+48 42 6590656', website = 'https://www.torimex.pl', company_description = 'Many years of successful business activity have solidified our position on both the domestic and foreign markets as a distributor of raw materials and products mainly for the rubber and plastic ...

Torimex Group Sp. z o.o. has been founded in the city of Lodz in 1994.', products_services = 'Chlorinated polyethylene (CPE), Chloroprene rubber (CR), Ethylene/propylene terpolymers (EPDM), Natural rubber, Nitrile rubber, Fire protection agents, Foaming agents, Stearates, Stearic acid, Waxes, Mineral fillers, Zinc oxide, Peroxides, All product categories', foundation_year = 'in the city of Lodz in 1994.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1173;

