-- Batch 17: Companies 161 to 170

-- GRAFE GmbH & Co. KG (ID: 1158)
UPDATE companies SET email = 'grafe@grafe.com', phone = '+49 36459 450', website = 'https://www.grafe.com', products_services = 'Acrylic glass (s. PMMA), Bioplastics, biobased, Bioplastics, biologically degradable, Bioplastics, cellulose based, Compounds/Blends, Compounds, natural fiber reinforced, Masterbatches, Polymethylmethacrylate (PMMA) and copolymers (s. acrylic glass), Antistatic agents, Agents biozides, Dispersing agents, Effect pigments, Flow auxiliaries, Lubricants, Additives for electrostatic spray paints, Additives, Matting agent, Nucleating agents, Impact modifiers, UV stabilizer, Subcontracting, All product categories', employees_count = '101 - 500', foundation_year = '1991', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics, Downloads, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on XING, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1158;

-- B & P Littleford LLC (ID: 1118)
UPDATE companies SET email = 'sales@bplittleford.com', phone = '+1 989 7571300', website = 'https://www.bplittleford.com', company_description = 'B&P Littleford designs and custom builds a wide spectrum of mixing, compounding, extruding, drying, reacting, and centrifugal separation equipment for large or small-scale manufacturing applications.

Our technologies are provided to industries such as plastics, ...', products_services = 'Polyarylate, Mixers, continuous type, for solids, Mixers, continuous type, for liquids, Mixers, batch type, for solids, Mixers, batch type, for liquids, Extrusion lines for compounding, Compounding lines, Extruders, Single screw extruders, Twin screw extruders, Multiple screw extruders, Extrusion lines for mono- and multifilaments, Extrusion lines for pipes and profiles, Extrusion lines for sheathing of pipes and cables, Extrusion lines for flexible hoses, Extrusion lines for rubber, Extrusion lines for composites, Machinery for processing/post processing of foam and parts, Heating and cooling units, All product categories', detailed_address = '1000 Hess Avenue', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Agriculture,, Other industries, Downloads, B&P Littleford TriVolution Compounder, B&P Littleford Mixing Process Guide, B&P Littleford Batch Mixers, B&P Littleford Continuous Mixers, B&P Littleford Vertical High Intensity Mixers & PVC Coolers, B&P Littleford Twin Screw Extruder, B&P Littleford Continuous Kneader, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1118;

-- Marubeni International (Europe) GmbH Chemical Group (ID: 1053)
UPDATE companies SET email = 'chemical-exhibition@marubeni.com', phone = '+49 211 3671-0', website = 'https://www.europe.marubeni.com', products_services = 'Acetal homo and copolymers (POM), Acrylonitrile/butadiene/styrene polymerblends, Acrylonitrile/butadiene/styrene copolymers, Acrylonitrile/styrene/acrylic ester copolymers (ASA), Barrier plastics, Bio-Polyamides, Compounds (Polymer blends), Electrically conductive plastics, Ethylene/tetrafluoroethylene copolymers (E/TFE), Polyarylamide (PA MXD6), Polycarbonate (PC), Polycarbonate blends, Polyetheretherketone (PEEK), Polyoxymethylne (POM) (s. acetal copolymers), Polytetrafluoroethylene (PTFE), Polyvinylidene chloride (PVDC), Polyvinylidene fluoride (PVDF), Tetrafluoroethylene/perfluoroalkylvinylether copolymers (PFA), Tetrafluoroethylene/perfluoropropylene copolymers (FEP), Thermoplastic elastomers, biobased, Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), SEBS-Blockcopolymer, Reinforcing materials, Antistatic agents, Solid lubricants, Lubricants, Coupling agents, Additives for electrostatic spray paints, Additives, Foaming agents, Impact modifiers, Whiskers, Decorative films, Purging compound, Products made by extrusion, Parts made by mechanical treating, Semi finished products of polytetrafluorethylene (PTFE), Semi finished products of polyvinylchloride (PVC), other and machined semi finished products / Pre-cut parts, Films, Parts from high performance thermoplastics, Compounds/Recyclates, Technical films, Separating foils, Subcontracting, All product categories', detailed_address = 'Marubeni Europe plc is a subsidiary of Marubeni Corporation, one of Japan’s leading general trading companies or “sogo shosha”.  Our trading activities span a broad range of goods and commodities, including machinery and equipment.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1053;

-- C. H. Erbslöh GmbH & Co. KG (ID: 1130)
UPDATE companies SET email = 'info.de@cherbsloeh.com', phone = '+49 2151 525-00', website = 'https://www.cherbsloeh.com', products_services = 'Antioxidants, Accelerators, Color Masterbatches, Coupling agents, Additives for electrostatic spray paints, Montan waxes, Pigment Black, Pigment Black Preparations, Impact modifiers, Processing auxiliaries, Vulcanisation accelerator, Waxes, Plasticiser, White pigments, Filter concentration, Kaolin, Mineral fillers, Talc, Wollastonite, Catalysts, Peroxides, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1130;

-- Symphony Environmental Ltd (ID: 1222)
UPDATE companies SET email = 'info@d2w.net', phone = '+44 208 2075900', website = 'https://www.d2w.net', products_services = 'Masterbatches, High-grade-resins, Protective materials for industry, Biodegradable additives, Agents biozides, Fire protection agents, Microbicides, Smoke density reductioners, All product categories', foundation_year = 'itself as a strong global business with over 74 di', target_groups = 'with a focus on the defence of both environmental and human health.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1222;

-- CAS, A division of the American Chemical Society (ID: 1132)
UPDATE companies SET email = 'help@cas.org', phone = '+1 614 4473731', website = 'https://www.cas.org', company_description = 'CAS connects the world’s scientific knowledge to accelerate breakthroughs that improve lives. We empower global innovators to efficiently navigate today’s complex data landscape and make confident decisions in each phase of the innovation journey. As a ...', products_services = 'Computer software services, All product categories', detailed_address = '2540, Olentangy River Road', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1907', target_groups = 'Other industries,, Trade, services, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1132;

-- EFLAYA SRL (ID: 1074)
UPDATE companies SET email = 'info@eflaya.com', phone = '+39 045 4500122', website = 'https://www.eflaya.com', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1074;

-- UBE Europe GmbH (ID: 1054)
UPDATE companies SET email = 'info@ube.com', phone = '+49 211 17883-0', website = 'https://www.ube.es', products_services = 'Barrier plastics, Compounds/Blends, Compounds (Polymer blends), Polyamides blends, Polyamid-Copolymer PA 06-66, Polyamide PA 12, Polyamide PA 06, Polybutylene terephthalate (PBT), Polypropylene, Polyurethane thermoplastic (PUR), Thermoplastic urethane blends TPE-U/TPU, Thermoplastic urethane TPE-U/TPU, Polyurethane, biobased, Thermoplastic PUR-elastomer, Polyimide resins, Polyethylene, low density, Polyethylene, high density, Polypropylene, Polyamide, Polypropylene fibres, Semi finished parts/products made from Polyimide, Fibreglass-reinforced plastic parts, All product categories', target_groups = 'with endless possibilities from the finite resources of coal to achieve lasting prosperity for the local community”, we continue to meet society’s needs through our main businesses: Chemicals & Machinery.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1054;

-- SHANDONG RUIFENG CHEMICAL CO., LTD (ID: 1100)
UPDATE companies SET email = 'frank@ruifengchemical.com', phone = '+86 186 15145488', website = 'https://www.ruifengchemical.com', company_description = 'Founded in 1994, the company is a national high-tech enterprise. In July 2011, we were listed on the Shenzhen Stock Exchange. Stock code: 300243

Specializing in the manufacturing and sales of PVC Additives, Engineering Plastic Additives and Compostable and ...', products_services = 'Additives, other, All product categories', foundation_year = 'in 1994, the company is a national high-tech enter', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1100;

-- Marangon Danilo & C. S.r.l. (ID: 1168)
UPDATE companies SET email = 'info@marangondanilo.it', phone = '+39 0444 697745', website = 'https://www.marangondanilo.it', products_services = 'Standard parts for moulds, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1168;

