-- Batch 8: Companies 71 to 80

-- Sitra S.p.A. Masterbatch (ID: 1195)
UPDATE companies SET email = 'commerciale@sitramasterbatch.com', phone = '+39 0776 562237', website = 'https://www.sitramasterbatch.com', products_services = 'Masterbatches, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1195;

-- BYK-Chemie GmbH (ID: 1171)
UPDATE companies SET email = 'info@byk.com', phone = '+49 281 670-0', website = 'https://www.byk.com', company_description = 'BYK is a leading global supplier of specialty chemicals. The company’s innovative additives and differentiated solutions optimize product and material properties as well as production and application processes. Among other things, BYK additives improve the scratch ...', products_services = 'Additives, other, Additive concentrates, Ageing stabilizers, Antisettling agents, Antifoam agents, Antislip agents, Antistatic agents, Fire protection agents, Dispersing agents, Coupling agents, Additives, Impact modifiers, Stabilizers, Flow control agents, Crosslinking agents, Waxes, All product categories', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1887', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Sports / leisure, Downloads, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1171;

-- Lehmann & Voss & Co. KG (ID: 1052)
UPDATE companies SET email = 'info@lehvoss.de', phone = '+49 40 44197-0', website = 'https://www.lehvoss.com', company_description = 'The LEHVOSS Group under the management of Lehmann&Voss&Co. is a group of companies in the chemicals sector that develops, produces and markets chemical and mineral specialities for various industrial clients. Lehmann&Voss&Co., Hamburg, was founded in 1894 as ...', products_services = 'Acetal homo and copolymers (POM), Acrylonitrile/butadiene/styrene polymerblends, Bioplastics, biobased, Compounds/Blends, Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Granulates, Masterbatches, Polyamide PA 11, Polyamide PA 12, Polyamide PA 66, Polyarylamide (PA MXD6), Polyaryletherketone (PAEK), Polybutylene terephthalate (PBT), Polycarbonate (PC), Polyetheretherketone (PEEK), Polyetherimide (PEI), Polyetherketone (PEK), Polyethersulfone (PES, PESU), Polyethylene terephthalate (PET), Polyketone, Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene sulfide (PPS), Polypropylene, Polyamide, Other thermoplastics, e.g. POM, PC, PBT, All product categories', foundation_year = 'in 1894 as a trading company. Since that time, the', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1052;

-- T. Michel Formenbau GmbH & Co. KG (ID: 1023)
UPDATE companies SET email = 'info@michel-form.de', phone = '+49 6772 9694-00', website = 'https://www.michel-form.de', products_services = 'Polystyrene expandable (EPS), Thermoplastic urethane TPE-U/TPU, Polyphenylene ether structural foams (PPE), Polypropylene-foams (EPP), Polystyrene foams, Parts made by foaming, Parts made by thermoforming, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for electrical engineering, Plastics products and parts for aviation, Plastics products and parts for medical engineering, Plastics products and parts for furniture appliances, Plastics products and parts for transport/packaging, Structural foam parts according to sample, drawing or customers tools, Preexpanders, foaming machinery for parts and blocks (for EPS, EPP, EPE), Machinery for processing/post processing of foam and parts, Moulds, Science and consulting, All product categories', employees_count = '31 - 100', foundation_year = '2000', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1023;

-- Beijing Phabuilder Biotechnology Co., Ltd. (ID: 1106)
UPDATE companies SET email = 'market@phabuilder.com', phone = '+86 185 15320363', website = 'https://www.phabuilder.com', company_description = 'PhaBuilder uses Halomonas (halophilic bacteria) as its core microbial chassis to build a fully integrated PHA industrial ecosystem that spans the entire value chain: strain design (PHAmily), scaled production (PHAdustry), material modification R&D (PHAbrary), and market ...', products_services = 'PHA (Polyhydroxyalkanoate), All product categories', detailed_address = 'No. 21, Zhaofeng 1st Street Zhao Quanying Town, Shunyi District', export_content = '> 75%', employees_count = '101 - 500', foundation_year = '2021', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Medical technology / precision engineering / optics, Downloads, PHA Biomaterial Product Catalog, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1106;

-- Gianeco srl (ID: 1069)
UPDATE companies SET email = 'info@gianeco.com', phone = '+39 011 9370420', website = 'https://www.gianeco.com', company_description = 'Gianeco S.r.l., founded in 2013 in Turin, gives new life to over 2,000 tons of recycled thermoplastic elastomers and bioplastics every year. We operate in 45+ countries, serving sectors like construction, agriculture, fashion, design, and packaging, promoting a true circular e...', products_services = 'PLA (polylactic acid, Polymilchsäure), Polybutylene succinate (PBS), Copolyester TPE-O, COPE, Thermoplastic urethane TPE-U/TPU, Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Olefin based thermoplastic elastomer, TPO, All product categories', export_content = '> 75%', foundation_year = '2013', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Construction / building and living,, Agriculture,, Sports / leisure,, Other industries,, Trade, services, Downloads, Brochure2024_gianeco_PRINT unite_compressed, EN - Company Profile_compressed-2024, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1069;

-- Cabot Switzerland GmbH (ID: 1197)
UPDATE companies SET email = 'cabot.plastics@cabotcorp.com', phone = '+41 52 630380', website = 'https://www.cabotcorp.com', company_description = 'Cabot Corporation is a leading global specialty chemicals and performance materials company headquartered in Boston, Massachusetts, USA, and has been providing innovative performance solutions to customers for over 140 years. We are a leading provider of specialty carbons, ...', products_services = 'Compounds/Blends, Compounds, natural fiber reinforced, Compounds (Polymer blends), Electrically conductive plastics, Masterbatches, Color Blacks (s. 1.10.99 Carbon black), Pigment Black, Pigment Black Preparations, Carbon black, Black pigments, All product categories', employees_count = '> 500', foundation_year = '1882', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, ICT,, Energy technology / photovoltaics,, Agriculture, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1197;

-- Clariant SE, Frankfurt am Main Muttenz Branch, Switzerland (ID: 1154)
UPDATE companies SET email = 'bernardo.rosa@clariant.com', phone = '+49 69 30580388', website = 'https://www.clariant.com', products_services = 'Additive concentrates, Amine sterically hindered, Antioxidants, Antistatic agents, Fire protection agents, Dispersing agents, Flow auxiliaries, Lubricants, Additives, Nucleating agents, Stabilizers, Release agents, Processing auxiliaries, Waxes, Mould release agents, All product categories', detailed_address = 'Clariant is a focused, sustainable, and innovative specialty chemical company based in Muttenz, near Basel/Switzerland. On 31 December 2021, Clariant totaled a staff number of 11 537 and recorded sales of CHF 4.372 in the fiscal year for its continuing businesses. The company reports in three business areas: Care Chemicals, Catalysis and Natural Resources. Clariant’s corporate strategy is led by the overarching purpose of ‘Greater chemistry – between people and planet’ and reflects the importance of connecting customer focus, innovation, sustainability, and people.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1154;

-- VEKA AG Ein Unternehmen der Laumann Gruppe (ID: 1029)
UPDATE companies SET email = 'info@vekaplan.de', phone = '+49 48324 02526-290', website = 'https://www.vekaplan.de', products_services = 'Products made by extrusion, Products/Preperation made by calendering, Parts made by laminating, Parts made by mechanical treating, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for office equipment/promotion, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for furniture appliances, Semi finished products of polyvinylchloride (PVC), other and machined semi finished products / Pre-cut parts, Boards and vulcanite boards, All product categories', employees_count = '. For this simple but decisive reason, VEKA focuses on the greatest possible qualification in the se', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1029;

-- IKS Schön GmbH (ID: 1014)
UPDATE companies SET email = 'kontakt@iks-schoen.de', phone = '+49 2131 38424-0', website = 'https://www.weltderkunststoffe.de', products_services = 'Parts made by mechanical treating, Plastics products and parts for plant building, Plastics products and parts for electrical engineering, Plastics products and parts for agriculture, Plastics products and parts for aviation, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of polytetrafluorethylene (PTFE), other and machined semi finished products / Pre-cut parts, Parts from standard plastics, Parts from engineering plastics, Parts from high performance thermoplastics, Laminated fabric and laminated paper, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 25%', employees_count = '11 - 30', foundation_year = '1974', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1014;

