-- Migration batch 4 - Companies update
-- Updates 61 to 80

UPDATE companies SET email = 'granulate@begra.de', phone = '+49 6848 7003-0', website = 'https://www.begra.de', products_services = 'Compounds/Blends, Wood Plastic Composites (WPC), Compounds (Polymer blends), Dry blend, Granulates, Polyvinyl chloride plasticised (PVC-P), Polyvinyl chloride rigid (PVC-U), Polyvinyl chloride expandable, Polyvinyl chloride blends, Polyvinyl chloride copolymers, Thermoplastic elastomers based on PVC, TPE/PVC, All product categories', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1972', target_groups = 'Plastic product manufacturing, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1092;

UPDATE companies SET email = 'info@kraiburg-tpe.com', phone = '+49 8638 98100', website = 'https://www.kraiburg.tpe.com', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', detailed_address = 'Rubber Street', employees_count = 'worldwide and production sites in Germany, the USA and Malaysia, the company offers a broad product ', foundation_year = 'in 2001 as an independent business unit of the KRA', target_groups = 'as well as for the strictly regulated medical sector.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1064;

UPDATE companies SET email = 'info@synchemer.com', phone = '+86 20 36685350', website = 'https://www.synchemer.com', company_description = 'SYNCHEMER CO., LIMITED is a High-Tech Enterprise, we are focusing on polymer additives developing, producing and selling. The products are widely used in automotive, construction, electronics, pharmaceutical industries… Benefit from Global and Domestic chemical production ...', products_services = 'Antioxidants, Fire protection agents, Light stabilisers (s. UV stabilizers), Nucleating agents, All product categories', detailed_address = 'Rm1723, Tower 1, Hongding Building No. 565 Yuncheng East Road', export_content = '> 75%', employees_count = '101 - 500', foundation_year = '2012', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Construction / building and living,, Energy technology / photovoltaics,, Agriculture, Downloads, SYNCHEMER CATALOGUE, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1162;

UPDATE companies SET email = 'polymers@kdfeddersen.com', phone = '+49 40 23507-535', website = 'https://kdfeddersen.global', company_description = 'With more than 75 years of experience, K.D. Feddersen Ueberseegesellschaft specializes in global polymer sourcing - offering the very best polymer, additive, or filler material for our customers. Our portfolio comprises a range of polymers, additives and filler materials for ...', products_services = 'Acetal homo and copolymers (POM), PLA (polylactic acid, Polymilchsäure), Copolyester TPE-O, COPE, Polyamide PA 06, Polycarbonate (PC), Polyethylene terephthalate (PET), Polyphenylene sulfide (PPS), All product categories', foundation_year = '1949', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Sports / leisure,, Other industries,, Trade, services, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1111;

UPDATE companies SET email = 'welcome@de.emsgrivory.com', phone = '+49 6078 7830', website = 'https://www.emsgrivory.com', products_services = 'Barrier plastics, Bioplastics, biobased, Bio-Polyamides, Compounds (Polymer blends), Electrically conductive plastics, Granulates, Optical polymers, Masterbatches, Polyamides blends, Polyamide PA 11, Polyamide PA 12, Polyamide PA 06, Polyamide PA 610, Polyamide PA 612, Polyamide PA 66, Polyamids PA 06-06-T, Polyketone, Polyamide 12-elastomer, Polyether block amide, Other thermoplastic elastomers, Polyamide, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1051;

UPDATE companies SET email = 'yh.chuang@lcygroup.com', phone = '+886 2 27631611', website = 'https://www.lcygroup.com', company_description = 'With a legacy dating back to 1915, LCY Chemical Corp is committed to reimagining science for a thriving tomorrow. We address human and societal challenges through circular economy solutions and contribute to sustainable industrial practices.', products_services = 'Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), All product categories', detailed_address = '3f, No. 85, Sec. 4, Bade Road', target_groups = 'Plastic product manufacturing,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Construction / building and living,, Medical technology / precision engineering / optics,, Sports / leisure,, Other industries, Downloads, LCY PCMA Catalogue_EN, LCY PP Catalogue__EN, LCY TPE Catalog-EN, LCY PP Health__EN, LCY TPV Catalogue_EN, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1078;

UPDATE companies SET email = 'info@marfran.com', phone = '+39 030 9860511', website = 'https://www.marfran.com', products_services = 'Compounds of styrenic block copolymers (SEBS, SBS, SIS…, TPE-S), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1079;

UPDATE companies SET email = 'danielle.harkness@plastekgroup.com', phone = '+44 1623 662233', website = 'https://www.plastekgroup.com', company_description = 'The Plastek Group is a trusted global supplier of premium quality injection moulding tools and plastic moulded and blow moulded components serving a wide range of industries including: Homecare, Personal Care, Infant Nutrition, Medical Devices, Plumbing & Heating, Food ...', products_services = 'Parts made by blow moulding, Parts made by injection moulding, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Parts from standard plastics, Parts from engineering plastics, Injection and compression moulds, Blow moulds, All product categories', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 75%', employees_count = '101 - 500', foundation_year = '1999', target_groups = 'Plastic product manufacturing, Downloads, Autumn Newsletter 24, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1034;

UPDATE companies SET email = 'julie@aspen-gs.com', phone = '+33 69002 048765686', website = 'https://www.aspen-gs.fr', products_services = 'PLA (polylactic acid, Polymilchsäure), Polybutyrate (PBAT), Compounds (Polymer blends), Masterbatches, Polyethylene PE-HD, Polyethylene PE-MD, Polypropylene, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1094;

UPDATE companies SET email = 'ruiankeji@ruiangeo.com', phone = '+86 400 0130200', website = 'https://www.ruiangeo.com', company_description = 'Gregeo’s Main Product: PBAT, PBS, TPEE, PCDL, PETG/PCTG and corresponding composite for different applications A comprehensive service provider specializing in technological innovation for new materials Ruian Group is a global-operated new materials service ...', products_services = 'Polybutyrate (PBAT), All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Agriculture,, Sports / leisure, Downloads, Brochure-Shandong Ruian Gregeo, Social networks, Visit the exhibitor on the following social networks, Visit us on DouYin, Visit us on LinkedIn, Visit us on WeChat, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1097;

UPDATE companies SET email = 'commerciale@sitramasterbatch.com', phone = '+39 0776 562237', website = 'https://www.sitramasterbatch.com', products_services = 'Masterbatches, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1195;

UPDATE companies SET email = 'info@byk.com', phone = '+49 281 670-0', website = 'https://www.byk.com', company_description = 'BYK is a leading global supplier of specialty chemicals. The company’s innovative additives and differentiated solutions optimize product and material properties as well as production and application processes. Among other things, BYK additives improve the scratch ...', products_services = 'Additives, other, Additive concentrates, Ageing stabilizers, Antisettling agents, Antifoam agents, Antislip agents, Antistatic agents, Fire protection agents, Dispersing agents, Coupling agents, Additives, Impact modifiers, Stabilizers, Flow control agents, Crosslinking agents, Waxes, All product categories', sales_volume = '> 100 Mill. US $', employees_count = '> 500', foundation_year = '1887', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Sports / leisure, Downloads, PDF file, PDF file, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on Instagram, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1171;

UPDATE companies SET email = 'info@lehvoss.de', phone = '+49 40 44197-0', website = 'https://www.lehvoss.com', company_description = 'The LEHVOSS Group under the management of Lehmann&Voss&Co. is a group of companies in the chemicals sector that develops, produces and markets chemical and mineral specialities for various industrial clients. Lehmann&Voss&Co., Hamburg, was founded in 1894 as ...', products_services = 'Acetal homo and copolymers (POM), Acrylonitrile/butadiene/styrene polymerblends, Bioplastics, biobased, Compounds/Blends, Self-reinforcing plastics (LCP=liquid crystal polymers), Electrically conductive plastics, Granulates, Masterbatches, Polyamide PA 11, Polyamide PA 12, Polyamide PA 66, Polyarylamide (PA MXD6), Polyaryletherketone (PAEK), Polybutylene terephthalate (PBT), Polycarbonate (PC), Polyetheretherketone (PEEK), Polyetherimide (PEI), Polyetherketone (PEK), Polyethersulfone (PES, PESU), Polyethylene terephthalate (PET), Polyketone, Polyoxymethylne (POM) (s. acetal copolymers), Polyphenylene sulfide (PPS), Polypropylene, Polyamide, Other thermoplastics, e.g. POM, PC, PBT, All product categories', foundation_year = 'in 1894 as a trading company. Since that time, the', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1052;

UPDATE companies SET email = 'info@michel-form.de', phone = '+49 6772 9694-00', website = 'https://www.michel-form.de', products_services = 'Polystyrene expandable (EPS), Thermoplastic urethane TPE-U/TPU, Polyphenylene ether structural foams (PPE), Polypropylene-foams (EPP), Polystyrene foams, Parts made by foaming, Parts made by thermoforming, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for household/consumer, Plastics products and parts for electrical engineering, Plastics products and parts for aviation, Plastics products and parts for medical engineering, Plastics products and parts for furniture appliances, Plastics products and parts for transport/packaging, Structural foam parts according to sample, drawing or customers tools, Preexpanders, foaming machinery for parts and blocks (for EPS, EPP, EPE), Machinery for processing/post processing of foam and parts, Moulds, Science and consulting, All product categories', employees_count = '31 - 100', foundation_year = '2000', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1023;

UPDATE companies SET email = 'market@phabuilder.com', phone = '+86 185 15320363', website = 'https://www.phabuilder.com', company_description = 'PhaBuilder uses Halomonas (halophilic bacteria) as its core microbial chassis to build a fully integrated PHA industrial ecosystem that spans the entire value chain: strain design (PHAmily), scaled production (PHAdustry), material modification R&D (PHAbrary), and market ...', products_services = 'PHA (Polyhydroxyalkanoate), All product categories', detailed_address = 'No. 21, Zhaofeng 1st Street Zhao Quanying Town, Shunyi District', export_content = '> 75%', employees_count = '101 - 500', foundation_year = '2021', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Medical technology / precision engineering / optics, Downloads, PHA Biomaterial Product Catalog, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1106;

UPDATE companies SET email = 'info@gianeco.com', phone = '+39 011 9370420', website = 'https://www.gianeco.com', company_description = 'Gianeco S.r.l., founded in 2013 in Turin, gives new life to over 2,000 tons of recycled thermoplastic elastomers and bioplastics every year. We operate in 45+ countries, serving sectors like construction, agriculture, fashion, design, and packaging, promoting a true circular e...', products_services = 'PLA (polylactic acid, Polymilchsäure), Polybutylene succinate (PBS), Copolyester TPE-O, COPE, Thermoplastic urethane TPE-U/TPU, Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), Olefin based thermoplastic elastomer, TPO, All product categories', export_content = '> 75%', foundation_year = '2013', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Construction / building and living,, Agriculture,, Sports / leisure,, Other industries,, Trade, services, Downloads, Brochure2024_gianeco_PRINT unite_compressed, EN - Company Profile_compressed-2024, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1069;

UPDATE companies SET email = 'cabot.plastics@cabotcorp.com', phone = '+41 52 630380', website = 'https://www.cabotcorp.com', company_description = 'Cabot Corporation is a leading global specialty chemicals and performance materials company headquartered in Boston, Massachusetts, USA, and has been providing innovative performance solutions to customers for over 140 years. We are a leading provider of specialty carbons, ...', products_services = 'Compounds/Blends, Compounds, natural fiber reinforced, Compounds (Polymer blends), Electrically conductive plastics, Masterbatches, Color Blacks (s. 1.10.99 Carbon black), Pigment Black, Pigment Black Preparations, Carbon black, Black pigments, All product categories', employees_count = '> 500', foundation_year = '1882', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, ICT,, Energy technology / photovoltaics,, Agriculture, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on X, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1197;

UPDATE companies SET email = 'bernardo.rosa@clariant.com', phone = '+49 69 30580388', website = 'https://www.clariant.com', products_services = 'Additive concentrates, Amine sterically hindered, Antioxidants, Antistatic agents, Fire protection agents, Dispersing agents, Flow auxiliaries, Lubricants, Additives, Nucleating agents, Stabilizers, Release agents, Processing auxiliaries, Waxes, Mould release agents, All product categories', detailed_address = 'Clariant is a focused, sustainable, and innovative specialty chemical company based in Muttenz, near Basel/Switzerland. On 31 December 2021, Clariant totaled a staff number of 11 537 and recorded sales of CHF 4.372 in the fiscal year for its continuing businesses. The company reports in three business areas: Care Chemicals, Catalysis and Natural Resources. Clariant’s corporate strategy is led by the overarching purpose of ‘Greater chemistry – between people and planet’ and reflects the importance of connecting customer focus, innovation, sustainability, and people.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1154;

UPDATE companies SET email = 'info@vekaplan.de', phone = '+49 48324 02526-290', website = 'https://www.vekaplan.de', products_services = 'Products made by extrusion, Products/Preperation made by calendering, Parts made by laminating, Parts made by mechanical treating, Plastics products and parts for automotive, Plastics products and parts for building applications, Plastics products and parts for office equipment/promotion, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for furniture appliances, Semi finished products of polyvinylchloride (PVC), other and machined semi finished products / Pre-cut parts, Boards and vulcanite boards, All product categories', employees_count = '. For this simple but decisive reason, VEKA focuses on the greatest possible qualification in the se', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1029;

UPDATE companies SET email = 'kontakt@iks-schoen.de', phone = '+49 2131 38424-0', website = 'https://www.weltderkunststoffe.de', products_services = 'Parts made by mechanical treating, Plastics products and parts for plant building, Plastics products and parts for electrical engineering, Plastics products and parts for agriculture, Plastics products and parts for aviation, Plastics products and parts for mechanical engineering, Plastics products and parts for medical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of polytetrafluorethylene (PTFE), other and machined semi finished products / Pre-cut parts, Parts from standard plastics, Parts from engineering plastics, Parts from high performance thermoplastics, Laminated fabric and laminated paper, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 25%', employees_count = '11 - 30', foundation_year = '1974', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1014;

