-- Migration batch 3 - Companies update
-- Updates 41 to 60

UPDATE companies SET email = 'monique.os-van@envalior.com', phone = '+31 6 30503410', website = 'https://envalior.com', company_description = 'At Envalior, we believe that our customers deserve only the highest quality products, services and support. Our commitment to quality is simple: zero defects. To achieve this, we follow a Total Quality Program that focuses on continuous improvement in everything we do. ...', products_services = 'Bio-Polyamides, Compounds (Polymer blends), Polyamide PA 46, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polyethylene terephthalate (PET), Polyphenylene sulfide (PPS), Thermoplastic elastomers based on PVC, TPE/PVC, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1093;

UPDATE companies SET email = 'info@ilpa-mp3.com', phone = '+39 051 6715811', website = 'https://www.mp3extrusion.com', products_services = 'Products made by extrusion, Parts made by thermoforming, Embossing, Plastics products and parts for automotive, Plastics products and parts for agriculture, Plastics products and parts for mechanical engineering, Plastics products and parts for food processing industry, Plastics products and parts for transport/packaging, Semi finished products of acryl-nitrile-butadiene (ABS), Semi finished products of polypropylene (PP), Semi finished products of polystyrene (PS), All product categories', export_content = 'In 2012, MP3 acquired 100% control of AMP Recycling, which boasts a long tradition in the field of p', foundation_year = 'in Italy in 1978. In 2016 it became MP3 Srl.', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1037;

UPDATE companies SET email = 'marketing.europe@ampacet.com', phone = '+352 29 20991', website = 'https://www.ampacet.com', company_description = 'Founded in 1937, Ampacet Corporation is a leading global masterbatch supplier committed to designing innovative custom colors, high performance additive solutions, multipurpose whites and blacks as well as sustainable masterbatches.', products_services = 'Masterbatches, Color Masterbatches, All product categories', foundation_year = ', Ampacet continues to drive innovation in the pla', target_groups = 'across the plastics value chain., Headquartered in Tarrytown, New York, Ampacet employs over 2,000 professionals worldwide and operates 20 manufacturing sites, including technical and color development centers in 17 countries throughout the Americas, Asia, and Europe. In Europe, the company runs seven production plants, with its regional headquarters located in Luxembourg., Ampacet is deeply committed to sustainability, consistently developing environmentally responsible solutions to address both environmental and societal challenges. Its growing portfolio of sustainable products reflects its proactive role in promoting circular economy practices and reducing environmental impact., Demonstrating its focus on specialized markets, Ampacet has recently introduced ELTech™ masterbatches, eng', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1115;

UPDATE companies SET email = 'exports@radhekrishnaexports.com', phone = '+91 79 9924204506', website = 'https://www.extrutech.in', company_description = 'Extrutech is a globally trusted manufacturer and exporter of advanced plastic extrusion machinery, specializing in screw & barrel systems, complete extrusion lines, and both upstream & downstream equipment. With over 32+ years of ...', products_services = 'Extruders, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '101 - 500', foundation_year = '1992', target_groups = 'Plastic product manufacturing, Downloads, Extrutech Digital Brochure, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1143;

UPDATE companies SET email = 'info@tepekimya.com', phone = '+90 216 5931920', website = 'https://www.tepekimya.com.tr', products_services = 'Additives, other, All product categories', export_content = 'ing its products to 60+ countries all across globe and developing its products to provide innovative', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1105;

UPDATE companies SET email = 'info@plastikakritis.com', phone = '+30 2810 308500', website = 'https://www.plastikakritis.com', company_description = 'Global Colors - part of the Plastika Kritis Group - is one of Europe’s largest masterbatch producers, delivering high-performance color, additive, white, and black masterbatches to the plastics industry worldwide. With production facilities in Greece, Romania, ...', products_services = 'Bioplastics, biologically degradable, Polybutyrate (PBAT), Compounds/Blends, Compounds (Polymer blends), Masterbatches, Additive concentrates, Antioxidants, Antistatic agents, Color Masterbatches, Light stabilisers (s. UV stabilizers), Additives, Carbon black, Cable compounds, Purging compound, All product categories', detailed_address = 'P. Street Iraklion Industrial Area', export_content = 's to more than 50 countries, Global Colors delivers consistent quality, cutting-edge technology, and', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1095;

UPDATE companies SET email = 'contact@traceless.eu', phone = '+49 170 5488213', website = 'https://www.traceless.eu', products_services = 'Bioplastics, biobased, Bioplastics, biologically degradable, All product categories', foundation_year = 'bioeconomy startup based in Hamburg, Germany. Wit', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1144;

UPDATE companies SET email = 'office@gmcolor.pl', phone = '+48 52 51535-35', website = 'https://www.gmcolor.pl', company_description = 'GM Color is family business, fully with Polish capital, operating on the domestic and European markets since 2004. We specialize in the production of high-quality color masterbatches and additives as well a compounds and regranulates. We focus on diversity, which is why our ...', products_services = 'Color Masterbatches, Additives, All product categories', employees_count = '101 - 500', foundation_year = '2004', target_groups = 'Plastic product manufacturing, Downloads, GM Color Folder EN 2024, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1212;

UPDATE companies SET email = 'info@ipbprinting.com', phone = '+31 497 621212', website = 'https://www.ipbprinting.com', company_description = 'iPB Printing specializes in the production of In Mould Labels (IML) and Flexible Packaging. For various applications, we offer you the ideal solution, with a focus on quality and processability.', products_services = 'Printing, All product categories', sales_volume = '5 - 20 Mill. US $', employees_count = '31 - 100', target_groups = 'Packaging / distribution, Downloads, General_IML_US, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1104;

UPDATE companies SET email = 'pstamp@peerless-coatings.co.uk', phone = '+44 1842 750333', website = 'https://www.peerless-coatings.co.uk', company_description = 'Striving for excellence in all that we do, we offer flexible, bespoke, protective hard coating solutions to all our customers the world over. Offering a complete chain solution from design, research & ...', employees_count = '31 - 100', target_groups = 'Plastic product manufacturing, Downloads, PEERLESS-Brochure June 2022-v2, Peerless – PRODUCTS HandOut A4 - 4pp – SINGLE PAGES, Social networks, Visit the exhibitor on the following social networks, Visit us on facebook, Visit us on LinkedIn, Visit us on X, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1169;

UPDATE companies SET email = 'info@bidielle.com', phone = '+39 0522 922521', website = 'https://www.bidielle.com', company_description = 'For over 40 years, BDL has been dedicated to the manufacturing of plastic injection molds. A constant commitment to quality has led to the creation of a flexible and dynamic structure, capable of offering each client tailored solutions to their specific needs.', products_services = 'Injection and compression moulds, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 50%', employees_count = '31 - 100', foundation_year = '1977', target_groups = 'Plastic product manufacturing,, Packaging / distribution,, Medical technology / precision engineering / optics, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1123;

UPDATE companies SET email = 'poliveira@vinmar.com', phone = '+31 61 5689952', website = 'https://axiaplastics.com', products_services = 'Polypropylene, Olefin based thermoplastic elastomer, TPO, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1089;

UPDATE companies SET email = 'daniela.quintero@dynasol.com', phone = '+1 281 8851700', website = 'https://dynasolgroup.com', products_services = 'Styrenic block copolymers SEBS, SBS, SIS…, TPE-S (pure polymers), All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1073;

UPDATE companies SET email = 'info@usmasterbatch.com', phone = '+84 24 6682771', website = 'https://usmasterbatch.com', products_services = 'Masterbatches, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1196;

UPDATE companies SET email = 'info@polymer-service.de', phone = '+49 40 30902-400', website = 'https://www.polymer-service.de', products_services = 'Acrylonitrile/butadiene/styrene polymerblends, Copolyester TPE-O, COPE, Ethylene/tetrafluoroethylene copolymers (E/TFE), Masterbatches, Polyamide PA 06, Polyamide PA 66, Polybutylene terephthalate (PBT), Polybutylene terephthalate blends, Polycarbonate (PC), Polycarbonate blends, Polyetheretherketone (PEEK), Polyethersulfone (PES, PESU), Polyketone, Polyphenylene sulfide (PPS), Polypropylene, Polysulfone (PSU), Polytetrafluoroethylene (PTFE), Polyvinylidene fluoride (PVDF), Reclaimed material, Tetrafluoroethylene/perfluoroalkylvinylether copolymers (PFA), Tetrafluoroethylene/perfluoropropylene copolymers (FEP), Thermoplastic elastomers dynamically crosslinked, TPE-V/TPV, Olefin based thermoplastic elastomer, TPO, Polyamide, Foaming agents, Subcontracting, All product categories', foundation_year = 'itself as a medium-sized, competent partner of the', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1084;

UPDATE companies SET email = 'info@aisa.com', phone = '+41 24 4820110', website = 'https://www.aisa.com', company_description = 'High-tech machines to produce plastic and laminated tube packaging—primarily used in the cosmetics, pharmaceutical, food, and personal care sectors—are our area of expertise. With over 60 years, AISA Automation Industrielle SA stands out for its know-how in development and ...', products_services = 'Parts made by injection moulding, Welding, Recycling plants for mixed waste, Injection moulding machines, multi-station, Compression and transfer moulding presses for plastics, Equipment for In-Mould-Labeling (IML), High-frequency welding machines, Science and consulting, All product categories', employees_count = '101 - 500', foundation_year = '1962', target_groups = 'Packaging / distribution, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on YouTube, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1112;

UPDATE companies SET email = 'ed@soltexpetro.com', phone = '+91 22 4063151502', website = 'https://www.soltexpetro.com', company_description = 'Soltex Petroproducts Ltd. is a leading producer of master batches from India with over 30 years of manufacturing expertise. We offer master batches like White, Black, Sodium & Color master batches as well as Additives like Anti block, ...', products_services = 'Color Masterbatches, All product categories', detailed_address = '5 ( Mumbai, Daman, Silvassa, Kolkata & Uttarakhand)', sales_volume = '20 - 100 Mill. US $', export_content = 'max. 25%', employees_count = '> 500', foundation_year = '1992', target_groups = 'Plastic product manufacturing,, Packaging / distribution, Downloads, Brochure, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, Visit us on WhatsApp, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1202;

UPDATE companies SET email = 'service@mj-additive.com', phone = '+49 2924 9706-0', website = 'https://www.mj-additive.com', products_services = 'Additives, other, Additive concentrates, Antiblocking agents, Antioxidants, Antislip agents, Antistatic agents, Dispersing agents, Flow auxiliaries, Lubricants, Light stabilisers (s. UV stabilizers), Additives, Nucleating agents, Stabilizers, UV stabilizer, Mould release agents, Raw materials, All product categories', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1157;

UPDATE companies SET email = 'isabella.yang@chinapelletizer.com', phone = '+852 852 66627518', company_description = 'CGC Technology International Ltd, was established in 2010, is specialized in the development and manufacturing of Underwater Pelletizers and Spare Parts for machinery used in the plastics industry, offering customized and innovative solutions to meet any need in underwater ...', products_services = 'Pelletizers, All product categories', sales_volume = '5 - 20 Mill. US $', export_content = 'max. 25%', employees_count = '101 - 500', foundation_year = '2010', target_groups = 'Machinery construction, Downloads, UWP® Underwater Pelletizing System, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1099;

UPDATE companies SET email = 'info@rowa-lack.de', phone = '+49 4101 706-01', website = 'https://www.rowa-lack.de', company_description = 'ROWA GmbH was founded in 1958 in Seevetal near Hamburg as a rubber processing company. From 1969, the company also produced high-quality coating systems, matting agent concentrates and ... Proven brand products and individual brands: basic components for a successful result.', products_services = 'Paint auxiliairies, Color Masterbatches, Matting agent, Crosslinking agents, Paints, coatings, Coatings, All product categories', employees_count = '31 - 100', foundation_year = '1958', target_groups = 'Plastic product manufacturing,, Chemical industry,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Other industries, Downloads, ROWA LACK Company Profile, Social networks, Visit the exhibitor on the following social networks, Visit us on LinkedIn, My notes, 0/400, Save', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1172;

