-- Test batch: 3 companies

UPDATE companies SET email = 'info.bopt.de@bruker.com', phone = '+49 7243 5042000', website = 'https://www.bruker.com', products_services = 'Measuring and test equipment for gaseous properties, Measuring and test equipment for optical properties, Plastic types identification equipment, All product categories', detailed_address = 'Today, worldwide more than 6,000 employees are working on this permanent challenge at over 90 locations on all continents. Bruker continues to build upon its extensive range of products and solutions, its broad base of installed systems and a strong reputation among its customers. Being one of the world''s leading analytical instrumentation companies, Bruker is strongly committed to further fully meet its customers’ needs as well as to continue to develop state-of-the-art technologies and innovative solutions for today''s analytical questions.', employees_count = 'are working on this permanent challenge at over 90 locations on all continents. Bruker continues to ', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1128;


UPDATE companies SET email = 'customerservice.geleen@intertek.com', phone = '+31 88 1268889', website = 'https://www.intertek.com', company_description = 'Intertek''s polymer labs provide testing, material qualification, consulting, compounding, processing, failure analysis and materials validation services to accelerate your polymer, recycled material and product development. www.intertek.com/polymers-plastics/', products_services = 'Science and consulting, All product categories', main_email = 'customerservice.geleen@intertek.com', main_phone = '+31 88 126 88 88', main_website = 'https://www.intertek.com/polymers-plastics/k-show/Understanding', target_groups = 'Plastic product manufacturing,, Chemical industry,, Rubber manufacturing / processing,, Machinery construction,, Packaging / distribution,, Vehicle construction / aerospace,, Electronics / electro technology,, Construction / building and living,, Medical technology / precision engineering / optics,, Energy technology / photovoltaics,, Sports / leisure,, Other industries,, Universities, technical colleges, Downloads, Intertek-CircularAssure-Circular-Economy-Solutions-For-Plastics, Intertek-Polymer-Testing-and-Inspection-Expertise, Brochure-Intertek-Food-Contact-Safety-Services, Intertek-Polymer-Processing-Injection-Moulding-Services-Catalogue, Packaging-Testing-Summary-2025-Postcard, CircularAssure-Summary-for-recycled-plastics-used-in-packaging-postcard, Intertek CircularAssure for the Aut', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1139;


UPDATE companies SET email = 'info@scjgroup.net', phone = '+91 11 26818181', website = 'https://www.scjindia.in', company_description = 'The SCJ group is a leader in the field of color and additive masterbatches, PVC Compounds, Co-Extruded Sheets and Telecom Cables, providing the plastic processing industry with quality products both for standard, as well as tailor made applications.', products_services = 'Masterbatches, Color Masterbatches, All product categories', detailed_address = '3/10 & 11, Okhla Industrial Area, Phase-1, New Delhi', foundation_year = ', SCJ is now poised on the threshold of creating a', data_source = 'profile_scraping', scraping_status = 'completed', last_detailed_scrape = NOW() WHERE id = 1201;


